// <auto-generated by tools/gen_apply.py/> Port of runtime/apply.cpp
using System.Runtime.CompilerServices;
namespace LeanSharp.Runtime;
public static unsafe partial class LeanRt {
public static Obj lean_curry(void* f, int n, Obj[] a, int off = 0) {
switch (n) {
case 1: return ((delegate*<Obj, Obj>)f)(a[off+0]);
case 2: return ((delegate*<Obj, Obj, Obj>)f)(a[off+0], a[off+1]);
case 3: return ((delegate*<Obj, Obj, Obj, Obj>)f)(a[off+0], a[off+1], a[off+2]);
case 4: return ((delegate*<Obj, Obj, Obj, Obj, Obj>)f)(a[off+0], a[off+1], a[off+2], a[off+3]);
case 5: return ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj>)f)(a[off+0], a[off+1], a[off+2], a[off+3], a[off+4]);
case 6: return ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj>)f)(a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5]);
case 7: return ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)f)(a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6]);
case 8: return ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)f)(a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6], a[off+7]);
case 9: return ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)f)(a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6], a[off+7], a[off+8]);
case 10: return ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)f)(a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6], a[off+7], a[off+8], a[off+9]);
case 11: return ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)f)(a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6], a[off+7], a[off+8], a[off+9], a[off+10]);
case 12: return ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)f)(a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6], a[off+7], a[off+8], a[off+9], a[off+10], a[off+11]);
case 13: return ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)f)(a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6], a[off+7], a[off+8], a[off+9], a[off+10], a[off+11], a[off+12]);
case 14: return ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)f)(a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6], a[off+7], a[off+8], a[off+9], a[off+10], a[off+11], a[off+12], a[off+13]);
case 15: return ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)f)(a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6], a[off+7], a[off+8], a[off+9], a[off+10], a[off+11], a[off+12], a[off+13], a[off+14]);
case 16: return ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)f)(a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6], a[off+7], a[off+8], a[off+9], a[off+10], a[off+11], a[off+12], a[off+13], a[off+14], a[off+15]);
default: { if (off == 0 && a.Length == n) return ((delegate*<Obj[], Obj>)f)(a); var b = new Obj[n]; Array.Copy(a, off, b, 0, n); return ((delegate*<Obj[], Obj>)f)(b); }
}
}
static Obj FixArgs(Obj f, Obj[] a, int off, int n) {
    var c = Unsafe.As<Closure>(f);
    int arity = c.m_arity, fixed_ = c.m_num_fixed;
    var r = new Closure { m_tag = (byte)LeanClosure, m_fun = c.m_fun, m_arity = (ushort)arity, m_num_fixed = (ushort)(fixed_ + n), m_objs = new Obj[fixed_ + n] };
    if (!lean_is_exclusive(f)) {
        for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); r.m_objs[i] = x; }
        lean_dec_ref(f);
    } else {
        Array.Copy(c.m_objs, r.m_objs, fixed_);
    }
    Array.Copy(a, off, r.m_objs, fixed_, n);
    return r;
}
public static Obj lean_apply_1(Obj f, Obj a1) {
if (f.m_tag == LeanBoxTag) { lean_dec(a1); return f; }
var c = Unsafe.As<Closure>(f);
int arity = c.m_arity; int fixed_ = c.m_num_fixed;
if (arity == fixed_ + 1) {
  var fx = c.m_objs;
  bool excl = lean_is_exclusive(f);
  if (!excl) { for (int i = 0; i < fixed_; i++) lean_inc(fx[i]); }
  Obj r;
  switch (arity) {
  case 1: r = ((delegate*<Obj, Obj>)c.m_fun)(a1); break;
  case 2: r = ((delegate*<Obj, Obj, Obj>)c.m_fun)(fx[0], a1); break;
  case 3: r = ((delegate*<Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], a1); break;
  case 4: r = ((delegate*<Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], a1); break;
  case 5: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], a1); break;
  case 6: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], a1); break;
  case 7: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], a1); break;
  case 8: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], a1); break;
  case 9: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], a1); break;
  case 10: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], a1); break;
  case 11: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], a1); break;
  case 12: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], fx[10], a1); break;
  case 13: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], fx[10], fx[11], a1); break;
  case 14: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], fx[10], fx[11], fx[12], a1); break;
  case 15: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], fx[10], fx[11], fx[12], fx[13], a1); break;
  case 16: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], fx[10], fx[11], fx[12], fx[13], fx[14], a1); break;
  default: {
    var args = new Obj[arity];
    Array.Copy(fx, args, fixed_);
    args[fixed_ + 0] = a1;
    r = ((delegate*<Obj[], Obj>)c.m_fun)(args); break; }
  }
  if (!excl) lean_dec_ref(f);
  return r;
} else if (arity < fixed_ + 1) {
  var as_ = new Obj[] { a1 };
  var args = new Obj[arity];
  for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
  Array.Copy(as_, 0, args, fixed_, arity - fixed_);
  var new_f = lean_curry(c.m_fun, arity, args);
  lean_dec_ref(f);
  return lean_apply_n_off(new_f, 1 + fixed_ - arity, as_, arity - fixed_);
} else {
  return FixArgs(f, new Obj[] { a1 }, 0, 1);
}
}
public static Obj lean_apply_2(Obj f, Obj a1, Obj a2) {
if (f.m_tag == LeanBoxTag) { lean_dec(a1); lean_dec(a2); return f; }
var c = Unsafe.As<Closure>(f);
int arity = c.m_arity; int fixed_ = c.m_num_fixed;
if (arity == fixed_ + 2) {
  var fx = c.m_objs;
  bool excl = lean_is_exclusive(f);
  if (!excl) { for (int i = 0; i < fixed_; i++) lean_inc(fx[i]); }
  Obj r;
  switch (arity) {
  case 2: r = ((delegate*<Obj, Obj, Obj>)c.m_fun)(a1, a2); break;
  case 3: r = ((delegate*<Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], a1, a2); break;
  case 4: r = ((delegate*<Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], a1, a2); break;
  case 5: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], a1, a2); break;
  case 6: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], a1, a2); break;
  case 7: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], a1, a2); break;
  case 8: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], a1, a2); break;
  case 9: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], a1, a2); break;
  case 10: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], a1, a2); break;
  case 11: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], a1, a2); break;
  case 12: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], a1, a2); break;
  case 13: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], fx[10], a1, a2); break;
  case 14: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], fx[10], fx[11], a1, a2); break;
  case 15: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], fx[10], fx[11], fx[12], a1, a2); break;
  case 16: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], fx[10], fx[11], fx[12], fx[13], a1, a2); break;
  default: {
    var args = new Obj[arity];
    Array.Copy(fx, args, fixed_);
    args[fixed_ + 0] = a1;
    args[fixed_ + 1] = a2;
    r = ((delegate*<Obj[], Obj>)c.m_fun)(args); break; }
  }
  if (!excl) lean_dec_ref(f);
  return r;
} else if (arity < fixed_ + 2) {
  var as_ = new Obj[] { a1, a2 };
  var args = new Obj[arity];
  for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
  Array.Copy(as_, 0, args, fixed_, arity - fixed_);
  var new_f = lean_curry(c.m_fun, arity, args);
  lean_dec_ref(f);
  return lean_apply_n_off(new_f, 2 + fixed_ - arity, as_, arity - fixed_);
} else {
  return FixArgs(f, new Obj[] { a1, a2 }, 0, 2);
}
}
public static Obj lean_apply_3(Obj f, Obj a1, Obj a2, Obj a3) {
if (f.m_tag == LeanBoxTag) { lean_dec(a1); lean_dec(a2); lean_dec(a3); return f; }
var c = Unsafe.As<Closure>(f);
int arity = c.m_arity; int fixed_ = c.m_num_fixed;
if (arity == fixed_ + 3) {
  var fx = c.m_objs;
  bool excl = lean_is_exclusive(f);
  if (!excl) { for (int i = 0; i < fixed_; i++) lean_inc(fx[i]); }
  Obj r;
  switch (arity) {
  case 3: r = ((delegate*<Obj, Obj, Obj, Obj>)c.m_fun)(a1, a2, a3); break;
  case 4: r = ((delegate*<Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], a1, a2, a3); break;
  case 5: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], a1, a2, a3); break;
  case 6: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], a1, a2, a3); break;
  case 7: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], a1, a2, a3); break;
  case 8: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], a1, a2, a3); break;
  case 9: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], a1, a2, a3); break;
  case 10: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], a1, a2, a3); break;
  case 11: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], a1, a2, a3); break;
  case 12: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], a1, a2, a3); break;
  case 13: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], a1, a2, a3); break;
  case 14: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], fx[10], a1, a2, a3); break;
  case 15: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], fx[10], fx[11], a1, a2, a3); break;
  case 16: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], fx[10], fx[11], fx[12], a1, a2, a3); break;
  default: {
    var args = new Obj[arity];
    Array.Copy(fx, args, fixed_);
    args[fixed_ + 0] = a1;
    args[fixed_ + 1] = a2;
    args[fixed_ + 2] = a3;
    r = ((delegate*<Obj[], Obj>)c.m_fun)(args); break; }
  }
  if (!excl) lean_dec_ref(f);
  return r;
} else if (arity < fixed_ + 3) {
  var as_ = new Obj[] { a1, a2, a3 };
  var args = new Obj[arity];
  for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
  Array.Copy(as_, 0, args, fixed_, arity - fixed_);
  var new_f = lean_curry(c.m_fun, arity, args);
  lean_dec_ref(f);
  return lean_apply_n_off(new_f, 3 + fixed_ - arity, as_, arity - fixed_);
} else {
  return FixArgs(f, new Obj[] { a1, a2, a3 }, 0, 3);
}
}
public static Obj lean_apply_4(Obj f, Obj a1, Obj a2, Obj a3, Obj a4) {
if (f.m_tag == LeanBoxTag) { lean_dec(a1); lean_dec(a2); lean_dec(a3); lean_dec(a4); return f; }
var c = Unsafe.As<Closure>(f);
int arity = c.m_arity; int fixed_ = c.m_num_fixed;
if (arity == fixed_ + 4) {
  var fx = c.m_objs;
  bool excl = lean_is_exclusive(f);
  if (!excl) { for (int i = 0; i < fixed_; i++) lean_inc(fx[i]); }
  Obj r;
  switch (arity) {
  case 4: r = ((delegate*<Obj, Obj, Obj, Obj, Obj>)c.m_fun)(a1, a2, a3, a4); break;
  case 5: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], a1, a2, a3, a4); break;
  case 6: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], a1, a2, a3, a4); break;
  case 7: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], a1, a2, a3, a4); break;
  case 8: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], a1, a2, a3, a4); break;
  case 9: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], a1, a2, a3, a4); break;
  case 10: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], a1, a2, a3, a4); break;
  case 11: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], a1, a2, a3, a4); break;
  case 12: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], a1, a2, a3, a4); break;
  case 13: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], a1, a2, a3, a4); break;
  case 14: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], a1, a2, a3, a4); break;
  case 15: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], fx[10], a1, a2, a3, a4); break;
  case 16: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], fx[10], fx[11], a1, a2, a3, a4); break;
  default: {
    var args = new Obj[arity];
    Array.Copy(fx, args, fixed_);
    args[fixed_ + 0] = a1;
    args[fixed_ + 1] = a2;
    args[fixed_ + 2] = a3;
    args[fixed_ + 3] = a4;
    r = ((delegate*<Obj[], Obj>)c.m_fun)(args); break; }
  }
  if (!excl) lean_dec_ref(f);
  return r;
} else if (arity < fixed_ + 4) {
  var as_ = new Obj[] { a1, a2, a3, a4 };
  var args = new Obj[arity];
  for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
  Array.Copy(as_, 0, args, fixed_, arity - fixed_);
  var new_f = lean_curry(c.m_fun, arity, args);
  lean_dec_ref(f);
  return lean_apply_n_off(new_f, 4 + fixed_ - arity, as_, arity - fixed_);
} else {
  return FixArgs(f, new Obj[] { a1, a2, a3, a4 }, 0, 4);
}
}
public static Obj lean_apply_5(Obj f, Obj a1, Obj a2, Obj a3, Obj a4, Obj a5) {
if (f.m_tag == LeanBoxTag) { lean_dec(a1); lean_dec(a2); lean_dec(a3); lean_dec(a4); lean_dec(a5); return f; }
var c = Unsafe.As<Closure>(f);
int arity = c.m_arity; int fixed_ = c.m_num_fixed;
if (arity == fixed_ + 5) {
  var fx = c.m_objs;
  bool excl = lean_is_exclusive(f);
  if (!excl) { for (int i = 0; i < fixed_; i++) lean_inc(fx[i]); }
  Obj r;
  switch (arity) {
  case 5: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(a1, a2, a3, a4, a5); break;
  case 6: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], a1, a2, a3, a4, a5); break;
  case 7: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], a1, a2, a3, a4, a5); break;
  case 8: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], a1, a2, a3, a4, a5); break;
  case 9: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], a1, a2, a3, a4, a5); break;
  case 10: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], a1, a2, a3, a4, a5); break;
  case 11: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], a1, a2, a3, a4, a5); break;
  case 12: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], a1, a2, a3, a4, a5); break;
  case 13: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], a1, a2, a3, a4, a5); break;
  case 14: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], a1, a2, a3, a4, a5); break;
  case 15: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], a1, a2, a3, a4, a5); break;
  case 16: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], fx[10], a1, a2, a3, a4, a5); break;
  default: {
    var args = new Obj[arity];
    Array.Copy(fx, args, fixed_);
    args[fixed_ + 0] = a1;
    args[fixed_ + 1] = a2;
    args[fixed_ + 2] = a3;
    args[fixed_ + 3] = a4;
    args[fixed_ + 4] = a5;
    r = ((delegate*<Obj[], Obj>)c.m_fun)(args); break; }
  }
  if (!excl) lean_dec_ref(f);
  return r;
} else if (arity < fixed_ + 5) {
  var as_ = new Obj[] { a1, a2, a3, a4, a5 };
  var args = new Obj[arity];
  for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
  Array.Copy(as_, 0, args, fixed_, arity - fixed_);
  var new_f = lean_curry(c.m_fun, arity, args);
  lean_dec_ref(f);
  return lean_apply_n_off(new_f, 5 + fixed_ - arity, as_, arity - fixed_);
} else {
  return FixArgs(f, new Obj[] { a1, a2, a3, a4, a5 }, 0, 5);
}
}
public static Obj lean_apply_6(Obj f, Obj a1, Obj a2, Obj a3, Obj a4, Obj a5, Obj a6) {
if (f.m_tag == LeanBoxTag) { lean_dec(a1); lean_dec(a2); lean_dec(a3); lean_dec(a4); lean_dec(a5); lean_dec(a6); return f; }
var c = Unsafe.As<Closure>(f);
int arity = c.m_arity; int fixed_ = c.m_num_fixed;
if (arity == fixed_ + 6) {
  var fx = c.m_objs;
  bool excl = lean_is_exclusive(f);
  if (!excl) { for (int i = 0; i < fixed_; i++) lean_inc(fx[i]); }
  Obj r;
  switch (arity) {
  case 6: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(a1, a2, a3, a4, a5, a6); break;
  case 7: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], a1, a2, a3, a4, a5, a6); break;
  case 8: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], a1, a2, a3, a4, a5, a6); break;
  case 9: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], a1, a2, a3, a4, a5, a6); break;
  case 10: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], a1, a2, a3, a4, a5, a6); break;
  case 11: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], a1, a2, a3, a4, a5, a6); break;
  case 12: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], a1, a2, a3, a4, a5, a6); break;
  case 13: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], a1, a2, a3, a4, a5, a6); break;
  case 14: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], a1, a2, a3, a4, a5, a6); break;
  case 15: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], a1, a2, a3, a4, a5, a6); break;
  case 16: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], fx[9], a1, a2, a3, a4, a5, a6); break;
  default: {
    var args = new Obj[arity];
    Array.Copy(fx, args, fixed_);
    args[fixed_ + 0] = a1;
    args[fixed_ + 1] = a2;
    args[fixed_ + 2] = a3;
    args[fixed_ + 3] = a4;
    args[fixed_ + 4] = a5;
    args[fixed_ + 5] = a6;
    r = ((delegate*<Obj[], Obj>)c.m_fun)(args); break; }
  }
  if (!excl) lean_dec_ref(f);
  return r;
} else if (arity < fixed_ + 6) {
  var as_ = new Obj[] { a1, a2, a3, a4, a5, a6 };
  var args = new Obj[arity];
  for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
  Array.Copy(as_, 0, args, fixed_, arity - fixed_);
  var new_f = lean_curry(c.m_fun, arity, args);
  lean_dec_ref(f);
  return lean_apply_n_off(new_f, 6 + fixed_ - arity, as_, arity - fixed_);
} else {
  return FixArgs(f, new Obj[] { a1, a2, a3, a4, a5, a6 }, 0, 6);
}
}
public static Obj lean_apply_7(Obj f, Obj a1, Obj a2, Obj a3, Obj a4, Obj a5, Obj a6, Obj a7) {
if (f.m_tag == LeanBoxTag) { lean_dec(a1); lean_dec(a2); lean_dec(a3); lean_dec(a4); lean_dec(a5); lean_dec(a6); lean_dec(a7); return f; }
var c = Unsafe.As<Closure>(f);
int arity = c.m_arity; int fixed_ = c.m_num_fixed;
if (arity == fixed_ + 7) {
  var fx = c.m_objs;
  bool excl = lean_is_exclusive(f);
  if (!excl) { for (int i = 0; i < fixed_; i++) lean_inc(fx[i]); }
  Obj r;
  switch (arity) {
  case 7: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(a1, a2, a3, a4, a5, a6, a7); break;
  case 8: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], a1, a2, a3, a4, a5, a6, a7); break;
  case 9: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], a1, a2, a3, a4, a5, a6, a7); break;
  case 10: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], a1, a2, a3, a4, a5, a6, a7); break;
  case 11: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], a1, a2, a3, a4, a5, a6, a7); break;
  case 12: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], a1, a2, a3, a4, a5, a6, a7); break;
  case 13: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], a1, a2, a3, a4, a5, a6, a7); break;
  case 14: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], a1, a2, a3, a4, a5, a6, a7); break;
  case 15: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], a1, a2, a3, a4, a5, a6, a7); break;
  case 16: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], fx[8], a1, a2, a3, a4, a5, a6, a7); break;
  default: {
    var args = new Obj[arity];
    Array.Copy(fx, args, fixed_);
    args[fixed_ + 0] = a1;
    args[fixed_ + 1] = a2;
    args[fixed_ + 2] = a3;
    args[fixed_ + 3] = a4;
    args[fixed_ + 4] = a5;
    args[fixed_ + 5] = a6;
    args[fixed_ + 6] = a7;
    r = ((delegate*<Obj[], Obj>)c.m_fun)(args); break; }
  }
  if (!excl) lean_dec_ref(f);
  return r;
} else if (arity < fixed_ + 7) {
  var as_ = new Obj[] { a1, a2, a3, a4, a5, a6, a7 };
  var args = new Obj[arity];
  for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
  Array.Copy(as_, 0, args, fixed_, arity - fixed_);
  var new_f = lean_curry(c.m_fun, arity, args);
  lean_dec_ref(f);
  return lean_apply_n_off(new_f, 7 + fixed_ - arity, as_, arity - fixed_);
} else {
  return FixArgs(f, new Obj[] { a1, a2, a3, a4, a5, a6, a7 }, 0, 7);
}
}
public static Obj lean_apply_8(Obj f, Obj a1, Obj a2, Obj a3, Obj a4, Obj a5, Obj a6, Obj a7, Obj a8) {
if (f.m_tag == LeanBoxTag) { lean_dec(a1); lean_dec(a2); lean_dec(a3); lean_dec(a4); lean_dec(a5); lean_dec(a6); lean_dec(a7); lean_dec(a8); return f; }
var c = Unsafe.As<Closure>(f);
int arity = c.m_arity; int fixed_ = c.m_num_fixed;
if (arity == fixed_ + 8) {
  var fx = c.m_objs;
  bool excl = lean_is_exclusive(f);
  if (!excl) { for (int i = 0; i < fixed_; i++) lean_inc(fx[i]); }
  Obj r;
  switch (arity) {
  case 8: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(a1, a2, a3, a4, a5, a6, a7, a8); break;
  case 9: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], a1, a2, a3, a4, a5, a6, a7, a8); break;
  case 10: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], a1, a2, a3, a4, a5, a6, a7, a8); break;
  case 11: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], a1, a2, a3, a4, a5, a6, a7, a8); break;
  case 12: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], a1, a2, a3, a4, a5, a6, a7, a8); break;
  case 13: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], a1, a2, a3, a4, a5, a6, a7, a8); break;
  case 14: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], a1, a2, a3, a4, a5, a6, a7, a8); break;
  case 15: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], a1, a2, a3, a4, a5, a6, a7, a8); break;
  case 16: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], fx[7], a1, a2, a3, a4, a5, a6, a7, a8); break;
  default: {
    var args = new Obj[arity];
    Array.Copy(fx, args, fixed_);
    args[fixed_ + 0] = a1;
    args[fixed_ + 1] = a2;
    args[fixed_ + 2] = a3;
    args[fixed_ + 3] = a4;
    args[fixed_ + 4] = a5;
    args[fixed_ + 5] = a6;
    args[fixed_ + 6] = a7;
    args[fixed_ + 7] = a8;
    r = ((delegate*<Obj[], Obj>)c.m_fun)(args); break; }
  }
  if (!excl) lean_dec_ref(f);
  return r;
} else if (arity < fixed_ + 8) {
  var as_ = new Obj[] { a1, a2, a3, a4, a5, a6, a7, a8 };
  var args = new Obj[arity];
  for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
  Array.Copy(as_, 0, args, fixed_, arity - fixed_);
  var new_f = lean_curry(c.m_fun, arity, args);
  lean_dec_ref(f);
  return lean_apply_n_off(new_f, 8 + fixed_ - arity, as_, arity - fixed_);
} else {
  return FixArgs(f, new Obj[] { a1, a2, a3, a4, a5, a6, a7, a8 }, 0, 8);
}
}
public static Obj lean_apply_9(Obj f, Obj a1, Obj a2, Obj a3, Obj a4, Obj a5, Obj a6, Obj a7, Obj a8, Obj a9) {
if (f.m_tag == LeanBoxTag) { lean_dec(a1); lean_dec(a2); lean_dec(a3); lean_dec(a4); lean_dec(a5); lean_dec(a6); lean_dec(a7); lean_dec(a8); lean_dec(a9); return f; }
var c = Unsafe.As<Closure>(f);
int arity = c.m_arity; int fixed_ = c.m_num_fixed;
if (arity == fixed_ + 9) {
  var fx = c.m_objs;
  bool excl = lean_is_exclusive(f);
  if (!excl) { for (int i = 0; i < fixed_; i++) lean_inc(fx[i]); }
  Obj r;
  switch (arity) {
  case 9: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(a1, a2, a3, a4, a5, a6, a7, a8, a9); break;
  case 10: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], a1, a2, a3, a4, a5, a6, a7, a8, a9); break;
  case 11: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], a1, a2, a3, a4, a5, a6, a7, a8, a9); break;
  case 12: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], a1, a2, a3, a4, a5, a6, a7, a8, a9); break;
  case 13: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], a1, a2, a3, a4, a5, a6, a7, a8, a9); break;
  case 14: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], a1, a2, a3, a4, a5, a6, a7, a8, a9); break;
  case 15: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], a1, a2, a3, a4, a5, a6, a7, a8, a9); break;
  case 16: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], fx[6], a1, a2, a3, a4, a5, a6, a7, a8, a9); break;
  default: {
    var args = new Obj[arity];
    Array.Copy(fx, args, fixed_);
    args[fixed_ + 0] = a1;
    args[fixed_ + 1] = a2;
    args[fixed_ + 2] = a3;
    args[fixed_ + 3] = a4;
    args[fixed_ + 4] = a5;
    args[fixed_ + 5] = a6;
    args[fixed_ + 6] = a7;
    args[fixed_ + 7] = a8;
    args[fixed_ + 8] = a9;
    r = ((delegate*<Obj[], Obj>)c.m_fun)(args); break; }
  }
  if (!excl) lean_dec_ref(f);
  return r;
} else if (arity < fixed_ + 9) {
  var as_ = new Obj[] { a1, a2, a3, a4, a5, a6, a7, a8, a9 };
  var args = new Obj[arity];
  for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
  Array.Copy(as_, 0, args, fixed_, arity - fixed_);
  var new_f = lean_curry(c.m_fun, arity, args);
  lean_dec_ref(f);
  return lean_apply_n_off(new_f, 9 + fixed_ - arity, as_, arity - fixed_);
} else {
  return FixArgs(f, new Obj[] { a1, a2, a3, a4, a5, a6, a7, a8, a9 }, 0, 9);
}
}
public static Obj lean_apply_10(Obj f, Obj a1, Obj a2, Obj a3, Obj a4, Obj a5, Obj a6, Obj a7, Obj a8, Obj a9, Obj a10) {
if (f.m_tag == LeanBoxTag) { lean_dec(a1); lean_dec(a2); lean_dec(a3); lean_dec(a4); lean_dec(a5); lean_dec(a6); lean_dec(a7); lean_dec(a8); lean_dec(a9); lean_dec(a10); return f; }
var c = Unsafe.As<Closure>(f);
int arity = c.m_arity; int fixed_ = c.m_num_fixed;
if (arity == fixed_ + 10) {
  var fx = c.m_objs;
  bool excl = lean_is_exclusive(f);
  if (!excl) { for (int i = 0; i < fixed_; i++) lean_inc(fx[i]); }
  Obj r;
  switch (arity) {
  case 10: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10); break;
  case 11: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10); break;
  case 12: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10); break;
  case 13: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10); break;
  case 14: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10); break;
  case 15: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10); break;
  case 16: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], fx[5], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10); break;
  default: {
    var args = new Obj[arity];
    Array.Copy(fx, args, fixed_);
    args[fixed_ + 0] = a1;
    args[fixed_ + 1] = a2;
    args[fixed_ + 2] = a3;
    args[fixed_ + 3] = a4;
    args[fixed_ + 4] = a5;
    args[fixed_ + 5] = a6;
    args[fixed_ + 6] = a7;
    args[fixed_ + 7] = a8;
    args[fixed_ + 8] = a9;
    args[fixed_ + 9] = a10;
    r = ((delegate*<Obj[], Obj>)c.m_fun)(args); break; }
  }
  if (!excl) lean_dec_ref(f);
  return r;
} else if (arity < fixed_ + 10) {
  var as_ = new Obj[] { a1, a2, a3, a4, a5, a6, a7, a8, a9, a10 };
  var args = new Obj[arity];
  for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
  Array.Copy(as_, 0, args, fixed_, arity - fixed_);
  var new_f = lean_curry(c.m_fun, arity, args);
  lean_dec_ref(f);
  return lean_apply_n_off(new_f, 10 + fixed_ - arity, as_, arity - fixed_);
} else {
  return FixArgs(f, new Obj[] { a1, a2, a3, a4, a5, a6, a7, a8, a9, a10 }, 0, 10);
}
}
public static Obj lean_apply_11(Obj f, Obj a1, Obj a2, Obj a3, Obj a4, Obj a5, Obj a6, Obj a7, Obj a8, Obj a9, Obj a10, Obj a11) {
if (f.m_tag == LeanBoxTag) { lean_dec(a1); lean_dec(a2); lean_dec(a3); lean_dec(a4); lean_dec(a5); lean_dec(a6); lean_dec(a7); lean_dec(a8); lean_dec(a9); lean_dec(a10); lean_dec(a11); return f; }
var c = Unsafe.As<Closure>(f);
int arity = c.m_arity; int fixed_ = c.m_num_fixed;
if (arity == fixed_ + 11) {
  var fx = c.m_objs;
  bool excl = lean_is_exclusive(f);
  if (!excl) { for (int i = 0; i < fixed_; i++) lean_inc(fx[i]); }
  Obj r;
  switch (arity) {
  case 11: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11); break;
  case 12: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11); break;
  case 13: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11); break;
  case 14: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11); break;
  case 15: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11); break;
  case 16: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], fx[4], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11); break;
  default: {
    var args = new Obj[arity];
    Array.Copy(fx, args, fixed_);
    args[fixed_ + 0] = a1;
    args[fixed_ + 1] = a2;
    args[fixed_ + 2] = a3;
    args[fixed_ + 3] = a4;
    args[fixed_ + 4] = a5;
    args[fixed_ + 5] = a6;
    args[fixed_ + 6] = a7;
    args[fixed_ + 7] = a8;
    args[fixed_ + 8] = a9;
    args[fixed_ + 9] = a10;
    args[fixed_ + 10] = a11;
    r = ((delegate*<Obj[], Obj>)c.m_fun)(args); break; }
  }
  if (!excl) lean_dec_ref(f);
  return r;
} else if (arity < fixed_ + 11) {
  var as_ = new Obj[] { a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11 };
  var args = new Obj[arity];
  for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
  Array.Copy(as_, 0, args, fixed_, arity - fixed_);
  var new_f = lean_curry(c.m_fun, arity, args);
  lean_dec_ref(f);
  return lean_apply_n_off(new_f, 11 + fixed_ - arity, as_, arity - fixed_);
} else {
  return FixArgs(f, new Obj[] { a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11 }, 0, 11);
}
}
public static Obj lean_apply_12(Obj f, Obj a1, Obj a2, Obj a3, Obj a4, Obj a5, Obj a6, Obj a7, Obj a8, Obj a9, Obj a10, Obj a11, Obj a12) {
if (f.m_tag == LeanBoxTag) { lean_dec(a1); lean_dec(a2); lean_dec(a3); lean_dec(a4); lean_dec(a5); lean_dec(a6); lean_dec(a7); lean_dec(a8); lean_dec(a9); lean_dec(a10); lean_dec(a11); lean_dec(a12); return f; }
var c = Unsafe.As<Closure>(f);
int arity = c.m_arity; int fixed_ = c.m_num_fixed;
if (arity == fixed_ + 12) {
  var fx = c.m_objs;
  bool excl = lean_is_exclusive(f);
  if (!excl) { for (int i = 0; i < fixed_; i++) lean_inc(fx[i]); }
  Obj r;
  switch (arity) {
  case 12: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12); break;
  case 13: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12); break;
  case 14: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12); break;
  case 15: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12); break;
  case 16: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], fx[3], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12); break;
  default: {
    var args = new Obj[arity];
    Array.Copy(fx, args, fixed_);
    args[fixed_ + 0] = a1;
    args[fixed_ + 1] = a2;
    args[fixed_ + 2] = a3;
    args[fixed_ + 3] = a4;
    args[fixed_ + 4] = a5;
    args[fixed_ + 5] = a6;
    args[fixed_ + 6] = a7;
    args[fixed_ + 7] = a8;
    args[fixed_ + 8] = a9;
    args[fixed_ + 9] = a10;
    args[fixed_ + 10] = a11;
    args[fixed_ + 11] = a12;
    r = ((delegate*<Obj[], Obj>)c.m_fun)(args); break; }
  }
  if (!excl) lean_dec_ref(f);
  return r;
} else if (arity < fixed_ + 12) {
  var as_ = new Obj[] { a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12 };
  var args = new Obj[arity];
  for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
  Array.Copy(as_, 0, args, fixed_, arity - fixed_);
  var new_f = lean_curry(c.m_fun, arity, args);
  lean_dec_ref(f);
  return lean_apply_n_off(new_f, 12 + fixed_ - arity, as_, arity - fixed_);
} else {
  return FixArgs(f, new Obj[] { a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12 }, 0, 12);
}
}
public static Obj lean_apply_13(Obj f, Obj a1, Obj a2, Obj a3, Obj a4, Obj a5, Obj a6, Obj a7, Obj a8, Obj a9, Obj a10, Obj a11, Obj a12, Obj a13) {
if (f.m_tag == LeanBoxTag) { lean_dec(a1); lean_dec(a2); lean_dec(a3); lean_dec(a4); lean_dec(a5); lean_dec(a6); lean_dec(a7); lean_dec(a8); lean_dec(a9); lean_dec(a10); lean_dec(a11); lean_dec(a12); lean_dec(a13); return f; }
var c = Unsafe.As<Closure>(f);
int arity = c.m_arity; int fixed_ = c.m_num_fixed;
if (arity == fixed_ + 13) {
  var fx = c.m_objs;
  bool excl = lean_is_exclusive(f);
  if (!excl) { for (int i = 0; i < fixed_; i++) lean_inc(fx[i]); }
  Obj r;
  switch (arity) {
  case 13: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13); break;
  case 14: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13); break;
  case 15: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13); break;
  case 16: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], fx[2], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13); break;
  default: {
    var args = new Obj[arity];
    Array.Copy(fx, args, fixed_);
    args[fixed_ + 0] = a1;
    args[fixed_ + 1] = a2;
    args[fixed_ + 2] = a3;
    args[fixed_ + 3] = a4;
    args[fixed_ + 4] = a5;
    args[fixed_ + 5] = a6;
    args[fixed_ + 6] = a7;
    args[fixed_ + 7] = a8;
    args[fixed_ + 8] = a9;
    args[fixed_ + 9] = a10;
    args[fixed_ + 10] = a11;
    args[fixed_ + 11] = a12;
    args[fixed_ + 12] = a13;
    r = ((delegate*<Obj[], Obj>)c.m_fun)(args); break; }
  }
  if (!excl) lean_dec_ref(f);
  return r;
} else if (arity < fixed_ + 13) {
  var as_ = new Obj[] { a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13 };
  var args = new Obj[arity];
  for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
  Array.Copy(as_, 0, args, fixed_, arity - fixed_);
  var new_f = lean_curry(c.m_fun, arity, args);
  lean_dec_ref(f);
  return lean_apply_n_off(new_f, 13 + fixed_ - arity, as_, arity - fixed_);
} else {
  return FixArgs(f, new Obj[] { a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13 }, 0, 13);
}
}
public static Obj lean_apply_14(Obj f, Obj a1, Obj a2, Obj a3, Obj a4, Obj a5, Obj a6, Obj a7, Obj a8, Obj a9, Obj a10, Obj a11, Obj a12, Obj a13, Obj a14) {
if (f.m_tag == LeanBoxTag) { lean_dec(a1); lean_dec(a2); lean_dec(a3); lean_dec(a4); lean_dec(a5); lean_dec(a6); lean_dec(a7); lean_dec(a8); lean_dec(a9); lean_dec(a10); lean_dec(a11); lean_dec(a12); lean_dec(a13); lean_dec(a14); return f; }
var c = Unsafe.As<Closure>(f);
int arity = c.m_arity; int fixed_ = c.m_num_fixed;
if (arity == fixed_ + 14) {
  var fx = c.m_objs;
  bool excl = lean_is_exclusive(f);
  if (!excl) { for (int i = 0; i < fixed_; i++) lean_inc(fx[i]); }
  Obj r;
  switch (arity) {
  case 14: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14); break;
  case 15: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14); break;
  case 16: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], fx[1], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14); break;
  default: {
    var args = new Obj[arity];
    Array.Copy(fx, args, fixed_);
    args[fixed_ + 0] = a1;
    args[fixed_ + 1] = a2;
    args[fixed_ + 2] = a3;
    args[fixed_ + 3] = a4;
    args[fixed_ + 4] = a5;
    args[fixed_ + 5] = a6;
    args[fixed_ + 6] = a7;
    args[fixed_ + 7] = a8;
    args[fixed_ + 8] = a9;
    args[fixed_ + 9] = a10;
    args[fixed_ + 10] = a11;
    args[fixed_ + 11] = a12;
    args[fixed_ + 12] = a13;
    args[fixed_ + 13] = a14;
    r = ((delegate*<Obj[], Obj>)c.m_fun)(args); break; }
  }
  if (!excl) lean_dec_ref(f);
  return r;
} else if (arity < fixed_ + 14) {
  var as_ = new Obj[] { a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14 };
  var args = new Obj[arity];
  for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
  Array.Copy(as_, 0, args, fixed_, arity - fixed_);
  var new_f = lean_curry(c.m_fun, arity, args);
  lean_dec_ref(f);
  return lean_apply_n_off(new_f, 14 + fixed_ - arity, as_, arity - fixed_);
} else {
  return FixArgs(f, new Obj[] { a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14 }, 0, 14);
}
}
public static Obj lean_apply_15(Obj f, Obj a1, Obj a2, Obj a3, Obj a4, Obj a5, Obj a6, Obj a7, Obj a8, Obj a9, Obj a10, Obj a11, Obj a12, Obj a13, Obj a14, Obj a15) {
if (f.m_tag == LeanBoxTag) { lean_dec(a1); lean_dec(a2); lean_dec(a3); lean_dec(a4); lean_dec(a5); lean_dec(a6); lean_dec(a7); lean_dec(a8); lean_dec(a9); lean_dec(a10); lean_dec(a11); lean_dec(a12); lean_dec(a13); lean_dec(a14); lean_dec(a15); return f; }
var c = Unsafe.As<Closure>(f);
int arity = c.m_arity; int fixed_ = c.m_num_fixed;
if (arity == fixed_ + 15) {
  var fx = c.m_objs;
  bool excl = lean_is_exclusive(f);
  if (!excl) { for (int i = 0; i < fixed_; i++) lean_inc(fx[i]); }
  Obj r;
  switch (arity) {
  case 15: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15); break;
  case 16: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(fx[0], a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15); break;
  default: {
    var args = new Obj[arity];
    Array.Copy(fx, args, fixed_);
    args[fixed_ + 0] = a1;
    args[fixed_ + 1] = a2;
    args[fixed_ + 2] = a3;
    args[fixed_ + 3] = a4;
    args[fixed_ + 4] = a5;
    args[fixed_ + 5] = a6;
    args[fixed_ + 6] = a7;
    args[fixed_ + 7] = a8;
    args[fixed_ + 8] = a9;
    args[fixed_ + 9] = a10;
    args[fixed_ + 10] = a11;
    args[fixed_ + 11] = a12;
    args[fixed_ + 12] = a13;
    args[fixed_ + 13] = a14;
    args[fixed_ + 14] = a15;
    r = ((delegate*<Obj[], Obj>)c.m_fun)(args); break; }
  }
  if (!excl) lean_dec_ref(f);
  return r;
} else if (arity < fixed_ + 15) {
  var as_ = new Obj[] { a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15 };
  var args = new Obj[arity];
  for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
  Array.Copy(as_, 0, args, fixed_, arity - fixed_);
  var new_f = lean_curry(c.m_fun, arity, args);
  lean_dec_ref(f);
  return lean_apply_n_off(new_f, 15 + fixed_ - arity, as_, arity - fixed_);
} else {
  return FixArgs(f, new Obj[] { a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15 }, 0, 15);
}
}
public static Obj lean_apply_16(Obj f, Obj a1, Obj a2, Obj a3, Obj a4, Obj a5, Obj a6, Obj a7, Obj a8, Obj a9, Obj a10, Obj a11, Obj a12, Obj a13, Obj a14, Obj a15, Obj a16) {
if (f.m_tag == LeanBoxTag) { lean_dec(a1); lean_dec(a2); lean_dec(a3); lean_dec(a4); lean_dec(a5); lean_dec(a6); lean_dec(a7); lean_dec(a8); lean_dec(a9); lean_dec(a10); lean_dec(a11); lean_dec(a12); lean_dec(a13); lean_dec(a14); lean_dec(a15); lean_dec(a16); return f; }
var c = Unsafe.As<Closure>(f);
int arity = c.m_arity; int fixed_ = c.m_num_fixed;
if (arity == fixed_ + 16) {
  var fx = c.m_objs;
  bool excl = lean_is_exclusive(f);
  if (!excl) { for (int i = 0; i < fixed_; i++) lean_inc(fx[i]); }
  Obj r;
  switch (arity) {
  case 16: r = ((delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj>)c.m_fun)(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16); break;
  default: {
    var args = new Obj[arity];
    Array.Copy(fx, args, fixed_);
    args[fixed_ + 0] = a1;
    args[fixed_ + 1] = a2;
    args[fixed_ + 2] = a3;
    args[fixed_ + 3] = a4;
    args[fixed_ + 4] = a5;
    args[fixed_ + 5] = a6;
    args[fixed_ + 6] = a7;
    args[fixed_ + 7] = a8;
    args[fixed_ + 8] = a9;
    args[fixed_ + 9] = a10;
    args[fixed_ + 10] = a11;
    args[fixed_ + 11] = a12;
    args[fixed_ + 12] = a13;
    args[fixed_ + 13] = a14;
    args[fixed_ + 14] = a15;
    args[fixed_ + 15] = a16;
    r = ((delegate*<Obj[], Obj>)c.m_fun)(args); break; }
  }
  if (!excl) lean_dec_ref(f);
  return r;
} else if (arity < fixed_ + 16) {
  var as_ = new Obj[] { a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16 };
  var args = new Obj[arity];
  for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
  Array.Copy(as_, 0, args, fixed_, arity - fixed_);
  var new_f = lean_curry(c.m_fun, arity, args);
  lean_dec_ref(f);
  return lean_apply_n_off(new_f, 16 + fixed_ - arity, as_, arity - fixed_);
} else {
  return FixArgs(f, new Obj[] { a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16 }, 0, 16);
}
}
public static Obj lean_apply_n_off(Obj f, int n, Obj[] a, int off) {
switch (n) {
case 1: return lean_apply_1(f, a[off+0]);
case 2: return lean_apply_2(f, a[off+0], a[off+1]);
case 3: return lean_apply_3(f, a[off+0], a[off+1], a[off+2]);
case 4: return lean_apply_4(f, a[off+0], a[off+1], a[off+2], a[off+3]);
case 5: return lean_apply_5(f, a[off+0], a[off+1], a[off+2], a[off+3], a[off+4]);
case 6: return lean_apply_6(f, a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5]);
case 7: return lean_apply_7(f, a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6]);
case 8: return lean_apply_8(f, a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6], a[off+7]);
case 9: return lean_apply_9(f, a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6], a[off+7], a[off+8]);
case 10: return lean_apply_10(f, a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6], a[off+7], a[off+8], a[off+9]);
case 11: return lean_apply_11(f, a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6], a[off+7], a[off+8], a[off+9], a[off+10]);
case 12: return lean_apply_12(f, a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6], a[off+7], a[off+8], a[off+9], a[off+10], a[off+11]);
case 13: return lean_apply_13(f, a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6], a[off+7], a[off+8], a[off+9], a[off+10], a[off+11], a[off+12]);
case 14: return lean_apply_14(f, a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6], a[off+7], a[off+8], a[off+9], a[off+10], a[off+11], a[off+12], a[off+13]);
case 15: return lean_apply_15(f, a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6], a[off+7], a[off+8], a[off+9], a[off+10], a[off+11], a[off+12], a[off+13], a[off+14]);
case 16: return lean_apply_16(f, a[off+0], a[off+1], a[off+2], a[off+3], a[off+4], a[off+5], a[off+6], a[off+7], a[off+8], a[off+9], a[off+10], a[off+11], a[off+12], a[off+13], a[off+14], a[off+15]);
default: return lean_apply_m_off(f, n, a, off);
}
}
public static Obj lean_apply_n(Obj f, uint n, Obj[] a) => lean_apply_n_off(f, (int)n, a, 0);
public static Obj lean_apply_m(Obj f, uint n, Obj[] a) => lean_apply_m_off(f, (int)n, a, 0);
public static Obj lean_apply_m_off(Obj f, int n, Obj[] a, int off) {
    if (f.m_tag == LeanBoxTag) { for (int i = 0; i < n; i++) lean_dec(a[off + i]); return f; }
    var c = Unsafe.As<Closure>(f);
    int arity = c.m_arity, fixed_ = c.m_num_fixed;
    if (arity == fixed_ + n) {
        var args = new Obj[arity];
        for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
        Array.Copy(a, off, args, fixed_, n);
        var r = ((delegate*<Obj[], Obj>)c.m_fun)(args);
        lean_dec_ref(f);
        return r;
    } else if (arity < fixed_ + n) {
        int m = arity - fixed_;
        Obj new_f;
        if (arity > LEAN_CLOSURE_MAX_ARGS) {
            var args = new Obj[arity];
            for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
            Array.Copy(a, off, args, fixed_, m);
            new_f = ((delegate*<Obj[], Obj>)c.m_fun)(args);
            lean_dec_ref(f);
        } else {
            new_f = lean_apply_n_off(f, m, a, off);
        }
        return lean_apply_n_off(new_f, n - m, a, off + m);
    } else {
        return FixArgs(f, a, off, n);
    }
}
}
