// Port of the UInt8/16/32/64, USize, Int8/16/32/64, ISize and Bool sections of `lean.h`
// (generated by a script; semantics mirror lean.h line by line: wrap-around arithmetic,
// division by zero yields 0, modulo by zero yields the dividend, shifts reduce the shift amount
// modulo the bit width (smod for signed types), MIN / -1 wraps).
//
// Signed fixed-width integers are passed around as their unsigned bit patterns, as in C.

using System.Numerics;
using System.Runtime.CompilerServices;

namespace LeanSharp.Runtime;

public static unsafe partial class LeanRt
{
    // ------------------------------------------------------------------ uint8

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_of_big_nat(Obj a) => unchecked((byte)NumbersInternal.Mod64(lean_nat_to_big(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_of_nat(Obj a) => unchecked(lean_is_scalar(a) ? (byte)lean_unbox(a) : lean_uint8_of_big_nat(a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_of_nat_mk(Obj a)
    {
        unchecked
        {
            byte r = lean_uint8_of_nat(a);
            lean_dec(a);
            return r;
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Obj lean_uint8_to_nat(byte a) => unchecked(lean_usize_to_nat((ulong)a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_add(byte a1, byte a2) => unchecked((byte)(a1 + a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_sub(byte a1, byte a2) => unchecked((byte)(a1 - a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_mul(byte a1, byte a2) => unchecked((byte)(a1 * a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_div(byte a1, byte a2) => unchecked(a2 == 0 ? (byte)0 : (byte)(a1 / a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_mod(byte a1, byte a2) => unchecked(a2 == 0 ? a1 : (byte)(a1 % a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_land(byte a, byte b) => unchecked((byte)(a & b));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_lor(byte a, byte b) => unchecked((byte)(a | b));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_xor(byte a, byte b) => unchecked((byte)(a ^ b));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_shift_left(byte a, byte b) => unchecked((byte)(a << (int)(b % 8)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_shift_right(byte a, byte b) => unchecked((byte)(a >> (int)(b % 8)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_complement(byte a) => unchecked((byte)~a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_neg(byte a) => unchecked((byte)(-a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_log2(byte a) => unchecked((byte)BitOperations.Log2(a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_dec_eq(byte a1, byte a2) => unchecked(a1 == a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_dec_lt(byte a1, byte a2) => unchecked(a1 < a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint8_dec_le(byte a1, byte a2) => unchecked(a1 <= a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint8_to_uint16(byte a) => unchecked((ushort)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint8_to_uint32(byte a) => unchecked((uint)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint8_to_uint64(byte a) => unchecked((ulong)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint8_to_usize(byte a) => unchecked((ulong)a);

    // ------------------------------------------------------------------ uint16

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint16_of_big_nat(Obj a) => unchecked((ushort)NumbersInternal.Mod64(lean_nat_to_big(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint16_of_nat(Obj a) => unchecked(lean_is_scalar(a) ? (ushort)lean_unbox(a) : lean_uint16_of_big_nat(a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint16_of_nat_mk(Obj a)
    {
        unchecked
        {
            ushort r = lean_uint16_of_nat(a);
            lean_dec(a);
            return r;
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Obj lean_uint16_to_nat(ushort a) => unchecked(lean_usize_to_nat((ulong)a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint16_add(ushort a1, ushort a2) => unchecked((ushort)(a1 + a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint16_sub(ushort a1, ushort a2) => unchecked((ushort)(a1 - a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint16_mul(ushort a1, ushort a2) => unchecked((ushort)(a1 * a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint16_div(ushort a1, ushort a2) => unchecked(a2 == 0 ? (ushort)0 : (ushort)(a1 / a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint16_mod(ushort a1, ushort a2) => unchecked(a2 == 0 ? a1 : (ushort)(a1 % a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint16_land(ushort a, ushort b) => unchecked((ushort)(a & b));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint16_lor(ushort a, ushort b) => unchecked((ushort)(a | b));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint16_xor(ushort a, ushort b) => unchecked((ushort)(a ^ b));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint16_shift_left(ushort a, ushort b) => unchecked((ushort)(a << (int)(b % 16)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint16_shift_right(ushort a, ushort b) => unchecked((ushort)(a >> (int)(b % 16)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint16_complement(ushort a) => unchecked((ushort)~a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint16_neg(ushort a) => unchecked((ushort)(-a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint16_log2(ushort a) => unchecked((ushort)BitOperations.Log2(a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint16_dec_eq(ushort a1, ushort a2) => unchecked(a1 == a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint16_dec_lt(ushort a1, ushort a2) => unchecked(a1 < a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint16_dec_le(ushort a1, ushort a2) => unchecked(a1 <= a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint16_to_uint8(ushort a) => unchecked((byte)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint16_to_uint32(ushort a) => unchecked((uint)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint16_to_uint64(ushort a) => unchecked((ulong)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint16_to_usize(ushort a) => unchecked((ulong)a);

    // ------------------------------------------------------------------ uint32

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint32_of_big_nat(Obj a) => unchecked((uint)NumbersInternal.Mod64(lean_nat_to_big(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint32_of_nat(Obj a) => unchecked(lean_is_scalar(a) ? (uint)lean_unbox(a) : lean_uint32_of_big_nat(a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint32_of_nat_mk(Obj a)
    {
        unchecked
        {
            uint r = lean_uint32_of_nat(a);
            lean_dec(a);
            return r;
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Obj lean_uint32_to_nat(uint a) => unchecked(lean_usize_to_nat((ulong)a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint32_add(uint a1, uint a2) => unchecked((uint)(a1 + a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint32_sub(uint a1, uint a2) => unchecked((uint)(a1 - a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint32_mul(uint a1, uint a2) => unchecked((uint)(a1 * a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint32_div(uint a1, uint a2) => unchecked(a2 == 0 ? (uint)0 : (uint)(a1 / a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint32_mod(uint a1, uint a2) => unchecked(a2 == 0 ? a1 : (uint)(a1 % a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint32_land(uint a, uint b) => unchecked((uint)(a & b));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint32_lor(uint a, uint b) => unchecked((uint)(a | b));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint32_xor(uint a, uint b) => unchecked((uint)(a ^ b));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint32_shift_left(uint a, uint b) => unchecked((uint)(a << (int)(b % 32)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint32_shift_right(uint a, uint b) => unchecked((uint)(a >> (int)(b % 32)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint32_complement(uint a) => unchecked((uint)~a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint32_neg(uint a) => unchecked((uint)(-a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint32_log2(uint a) => unchecked((uint)BitOperations.Log2(a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint32_dec_eq(uint a1, uint a2) => unchecked(a1 == a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint32_dec_lt(uint a1, uint a2) => unchecked(a1 < a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint32_dec_le(uint a1, uint a2) => unchecked(a1 <= a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint32_to_uint8(uint a) => unchecked((byte)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint32_to_uint16(uint a) => unchecked((ushort)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint32_to_uint64(uint a) => unchecked((ulong)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint32_to_usize(uint a) => unchecked((ulong)a);

    // ------------------------------------------------------------------ uint64

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint64_of_big_nat(Obj a) => unchecked((ulong)NumbersInternal.Mod64(lean_nat_to_big(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint64_of_nat(Obj a) => unchecked(lean_is_scalar(a) ? (ulong)lean_unbox(a) : lean_uint64_of_big_nat(a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint64_of_nat_mk(Obj a)
    {
        unchecked
        {
            ulong r = lean_uint64_of_nat(a);
            lean_dec(a);
            return r;
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint64_add(ulong a1, ulong a2) => unchecked((ulong)(a1 + a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint64_sub(ulong a1, ulong a2) => unchecked((ulong)(a1 - a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint64_mul(ulong a1, ulong a2) => unchecked((ulong)(a1 * a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint64_div(ulong a1, ulong a2) => unchecked(a2 == 0 ? (ulong)0 : (ulong)(a1 / a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint64_mod(ulong a1, ulong a2) => unchecked(a2 == 0 ? a1 : (ulong)(a1 % a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint64_land(ulong a, ulong b) => unchecked((ulong)(a & b));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint64_lor(ulong a, ulong b) => unchecked((ulong)(a | b));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint64_xor(ulong a, ulong b) => unchecked((ulong)(a ^ b));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint64_shift_left(ulong a, ulong b) => unchecked((ulong)(a << (int)(b % 64)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint64_shift_right(ulong a, ulong b) => unchecked((ulong)(a >> (int)(b % 64)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint64_complement(ulong a) => unchecked((ulong)~a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint64_neg(ulong a) => unchecked((ulong)(0UL - a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint64_log2(ulong a) => unchecked((ulong)BitOperations.Log2(a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint64_dec_eq(ulong a1, ulong a2) => unchecked(a1 == a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint64_dec_lt(ulong a1, ulong a2) => unchecked(a1 < a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint64_dec_le(ulong a1, ulong a2) => unchecked(a1 <= a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_uint64_to_uint8(ulong a) => unchecked((byte)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_uint64_to_uint16(ulong a) => unchecked((ushort)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_uint64_to_uint32(ulong a) => unchecked((uint)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_uint64_to_usize(ulong a) => unchecked((ulong)a);

    // ------------------------------------------------------------------ usize

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_usize_of_big_nat(Obj a) => unchecked(NumbersInternal.Mod64(lean_nat_to_big(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_usize_of_nat(Obj a) => unchecked(lean_is_scalar(a) ? (ulong)lean_unbox(a) : lean_usize_of_big_nat(a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_usize_of_nat_mk(Obj a)
    {
        unchecked
        {
            ulong r = lean_usize_of_nat(a);
            lean_dec(a);
            return r;
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_usize_add(ulong a1, ulong a2) => unchecked((ulong)(a1 + a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_usize_sub(ulong a1, ulong a2) => unchecked((ulong)(a1 - a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_usize_mul(ulong a1, ulong a2) => unchecked((ulong)(a1 * a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_usize_div(ulong a1, ulong a2) => unchecked(a2 == 0 ? (ulong)0 : (ulong)(a1 / a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_usize_mod(ulong a1, ulong a2) => unchecked(a2 == 0 ? a1 : (ulong)(a1 % a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_usize_land(ulong a, ulong b) => unchecked((ulong)(a & b));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_usize_lor(ulong a, ulong b) => unchecked((ulong)(a | b));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_usize_xor(ulong a, ulong b) => unchecked((ulong)(a ^ b));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_usize_shift_left(ulong a, ulong b) => unchecked((ulong)(a << (int)(b % 64)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_usize_shift_right(ulong a, ulong b) => unchecked((ulong)(a >> (int)(b % 64)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_usize_complement(ulong a) => unchecked((ulong)~a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_usize_neg(ulong a) => unchecked((ulong)(0UL - a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_usize_log2(ulong a) => unchecked((ulong)BitOperations.Log2(a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_usize_dec_eq(ulong a1, ulong a2) => unchecked(a1 == a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_usize_dec_lt(ulong a1, ulong a2) => unchecked(a1 < a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_usize_dec_le(ulong a1, ulong a2) => unchecked(a1 <= a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_usize_to_uint8(ulong a) => unchecked((byte)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_usize_to_uint16(ulong a) => unchecked((ushort)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_usize_to_uint32(ulong a) => unchecked((uint)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_usize_to_uint64(ulong a) => unchecked((ulong)a);

    public static ulong lean_uint64_mix_hash(ulong h, ulong k) => LeanHash.Mix(h, k);

    // ------------------------------------------------------------------ int8

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static sbyte lean_int8_of_big_int(Obj a) => unchecked((sbyte)NumbersInternal.Mod64(lean_nat_to_big(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int8_of_int(Obj a) => unchecked((byte)(lean_is_scalar(a) ? (sbyte)lean_scalar_to_int64(a) : lean_int8_of_big_int(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int8_of_nat(Obj a) => unchecked((byte)(lean_is_scalar(a) ? (sbyte)lean_unbox(a) : lean_int8_of_big_int(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Obj lean_int8_to_int(byte a) => unchecked(lean_int64_to_int((sbyte)a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int8_neg(byte a) => unchecked((byte)(-a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int8_add(byte a1, byte a2) => unchecked((byte)(a1 + a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int8_sub(byte a1, byte a2) => unchecked((byte)(a1 - a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int8_mul(byte a1, byte a2) => unchecked((byte)(a1 * a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int8_div(byte a1, byte a2)
    {
        unchecked
        {
            sbyte lhs = (sbyte)a1;
            sbyte rhs = (sbyte)a2;
            if (rhs == 0) return 0;
            return (byte)((short)lhs / (short)rhs);
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int8_mod(byte a1, byte a2)
    {
        unchecked
        {
            sbyte lhs = (sbyte)a1;
            sbyte rhs = (sbyte)a2;
            if (rhs == 0) return (byte)lhs;
            return (byte)((short)lhs % (short)rhs);
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int8_land(byte a1, byte a2) => unchecked((byte)((sbyte)a1 & (sbyte)a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int8_lor(byte a1, byte a2) => unchecked((byte)((sbyte)a1 | (sbyte)a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int8_xor(byte a1, byte a2) => unchecked((byte)((sbyte)a1 ^ (sbyte)a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int8_shift_right(byte a1, byte a2)
    {
        unchecked
        {
            sbyte lhs = (sbyte)a1;
            int rhs = (((sbyte)a2 % 8) + 8) % 8; // smod 8
            return (byte)(lhs >> rhs);
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int8_shift_left(byte a1, byte a2)
    {
        unchecked
        {
            int rhs = (((sbyte)a2 % 8) + 8) % 8; // smod 8
            return (byte)(a1 << rhs);
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int8_complement(byte a) => unchecked((byte)~(sbyte)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int8_abs(byte a) => unchecked((sbyte)a < 0 ? (byte)(-a) : a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int8_dec_eq(byte a1, byte a2) => unchecked((sbyte)a1 == (sbyte)a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int8_dec_lt(byte a1, byte a2) => unchecked((sbyte)a1 < (sbyte)a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int8_dec_le(byte a1, byte a2) => unchecked((sbyte)a1 <= (sbyte)a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_int8_to_int16(byte a) => unchecked((ushort)(short)(sbyte)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_int8_to_int32(byte a) => unchecked((uint)(int)(sbyte)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int8_to_int64(byte a) => unchecked((ulong)(long)(sbyte)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int8_to_isize(byte a) => unchecked((ulong)(long)(sbyte)a);

    // ------------------------------------------------------------------ int16

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static short lean_int16_of_big_int(Obj a) => unchecked((short)NumbersInternal.Mod64(lean_nat_to_big(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_int16_of_int(Obj a) => unchecked((ushort)(lean_is_scalar(a) ? (short)lean_scalar_to_int64(a) : lean_int16_of_big_int(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_int16_of_nat(Obj a) => unchecked((ushort)(lean_is_scalar(a) ? (short)lean_unbox(a) : lean_int16_of_big_int(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Obj lean_int16_to_int(ushort a) => unchecked(lean_int64_to_int((short)a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_int16_neg(ushort a) => unchecked((ushort)(-a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_int16_add(ushort a1, ushort a2) => unchecked((ushort)(a1 + a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_int16_sub(ushort a1, ushort a2) => unchecked((ushort)(a1 - a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_int16_mul(ushort a1, ushort a2) => unchecked((ushort)(a1 * a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_int16_div(ushort a1, ushort a2)
    {
        unchecked
        {
            short lhs = (short)a1;
            short rhs = (short)a2;
            if (rhs == 0) return 0;
            return (ushort)((int)lhs / (int)rhs);
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_int16_mod(ushort a1, ushort a2)
    {
        unchecked
        {
            short lhs = (short)a1;
            short rhs = (short)a2;
            if (rhs == 0) return (ushort)lhs;
            return (ushort)((int)lhs % (int)rhs);
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_int16_land(ushort a1, ushort a2) => unchecked((ushort)((short)a1 & (short)a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_int16_lor(ushort a1, ushort a2) => unchecked((ushort)((short)a1 | (short)a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_int16_xor(ushort a1, ushort a2) => unchecked((ushort)((short)a1 ^ (short)a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_int16_shift_right(ushort a1, ushort a2)
    {
        unchecked
        {
            short lhs = (short)a1;
            int rhs = (((short)a2 % 16) + 16) % 16; // smod 16
            return (ushort)(lhs >> rhs);
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_int16_shift_left(ushort a1, ushort a2)
    {
        unchecked
        {
            int rhs = (((short)a2 % 16) + 16) % 16; // smod 16
            return (ushort)(a1 << rhs);
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_int16_complement(ushort a) => unchecked((ushort)~(short)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_int16_abs(ushort a) => unchecked((short)a < 0 ? (ushort)(-a) : a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int16_dec_eq(ushort a1, ushort a2) => unchecked((short)a1 == (short)a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int16_dec_lt(ushort a1, ushort a2) => unchecked((short)a1 < (short)a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int16_dec_le(ushort a1, ushort a2) => unchecked((short)a1 <= (short)a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int16_to_int8(ushort a) => unchecked((byte)(sbyte)(short)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_int16_to_int32(ushort a) => unchecked((uint)(int)(short)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int16_to_int64(ushort a) => unchecked((ulong)(long)(short)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int16_to_isize(ushort a) => unchecked((ulong)(long)(short)a);

    // ------------------------------------------------------------------ int32

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int lean_int32_of_big_int(Obj a) => unchecked((int)NumbersInternal.Mod64(lean_nat_to_big(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_int32_of_int(Obj a) => unchecked((uint)(lean_is_scalar(a) ? (int)lean_scalar_to_int64(a) : lean_int32_of_big_int(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_int32_of_nat(Obj a) => unchecked((uint)(lean_is_scalar(a) ? (int)lean_unbox(a) : lean_int32_of_big_int(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Obj lean_int32_to_int(uint a) => unchecked(lean_int64_to_int((int)a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_int32_neg(uint a) => unchecked((uint)(-a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_int32_add(uint a1, uint a2) => unchecked((uint)(a1 + a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_int32_sub(uint a1, uint a2) => unchecked((uint)(a1 - a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_int32_mul(uint a1, uint a2) => unchecked((uint)(a1 * a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_int32_div(uint a1, uint a2)
    {
        unchecked
        {
            int lhs = (int)a1;
            int rhs = (int)a2;
            if (rhs == 0) return 0;
            return (uint)((long)lhs / (long)rhs);
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_int32_mod(uint a1, uint a2)
    {
        unchecked
        {
            int lhs = (int)a1;
            int rhs = (int)a2;
            if (rhs == 0) return (uint)lhs;
            return (uint)((long)lhs % (long)rhs);
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_int32_land(uint a1, uint a2) => unchecked((uint)((int)a1 & (int)a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_int32_lor(uint a1, uint a2) => unchecked((uint)((int)a1 | (int)a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_int32_xor(uint a1, uint a2) => unchecked((uint)((int)a1 ^ (int)a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_int32_shift_right(uint a1, uint a2)
    {
        unchecked
        {
            int lhs = (int)a1;
            int rhs = (((int)a2 % 32) + 32) % 32; // smod 32
            return (uint)(lhs >> rhs);
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_int32_shift_left(uint a1, uint a2)
    {
        unchecked
        {
            int rhs = (((int)a2 % 32) + 32) % 32; // smod 32
            return (uint)(a1 << rhs);
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_int32_complement(uint a) => unchecked((uint)~(int)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_int32_abs(uint a) => unchecked((int)a < 0 ? (uint)(-a) : a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int32_dec_eq(uint a1, uint a2) => unchecked((int)a1 == (int)a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int32_dec_lt(uint a1, uint a2) => unchecked((int)a1 < (int)a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int32_dec_le(uint a1, uint a2) => unchecked((int)a1 <= (int)a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int32_to_int8(uint a) => unchecked((byte)(sbyte)(int)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_int32_to_int16(uint a) => unchecked((ushort)(short)(int)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int32_to_int64(uint a) => unchecked((ulong)(long)(int)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int32_to_isize(uint a) => unchecked((ulong)(long)(int)a);

    // ------------------------------------------------------------------ int64

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static long lean_int64_of_big_int(Obj a) => unchecked((long)NumbersInternal.Mod64(lean_nat_to_big(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int64_of_int(Obj a) => unchecked((ulong)(lean_is_scalar(a) ? (long)lean_scalar_to_int64(a) : lean_int64_of_big_int(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int64_of_nat(Obj a) => unchecked((ulong)(lean_is_scalar(a) ? (long)lean_unbox(a) : lean_int64_of_big_int(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Obj lean_int64_to_int_sint(ulong a) => unchecked(lean_int64_to_int((long)a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int64_neg(ulong a) => unchecked((ulong)(0UL - a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int64_add(ulong a1, ulong a2) => unchecked((ulong)(a1 + a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int64_sub(ulong a1, ulong a2) => unchecked((ulong)(a1 - a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int64_mul(ulong a1, ulong a2) => unchecked((ulong)(a1 * a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int64_div(ulong a1, ulong a2)
    {
        unchecked
        {
            long lhs = (long)a1;
            long rhs = (long)a2;
            if (rhs == 0) return 0;
            if (lhs == long.MinValue && rhs == -1) return (ulong)long.MinValue;
            return (ulong)(lhs / rhs);
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int64_mod(ulong a1, ulong a2)
    {
        unchecked
        {
            long lhs = (long)a1;
            long rhs = (long)a2;
            if (rhs == 0) return (ulong)lhs;
            if (lhs == long.MinValue && rhs == -1) return 0;
            return (ulong)(lhs % rhs);
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int64_land(ulong a1, ulong a2) => unchecked((ulong)((long)a1 & (long)a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int64_lor(ulong a1, ulong a2) => unchecked((ulong)((long)a1 | (long)a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int64_xor(ulong a1, ulong a2) => unchecked((ulong)((long)a1 ^ (long)a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int64_shift_right(ulong a1, ulong a2)
    {
        unchecked
        {
            long lhs = (long)a1;
            long rhs = (((long)a2 % 64) + 64) % 64; // smod 64
            return (ulong)(lhs >> (int)rhs);
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int64_shift_left(ulong a1, ulong a2)
    {
        unchecked
        {
            long rhs = (((long)a2 % 64) + 64) % 64; // smod 64
            return a1 << (int)rhs;
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int64_complement(ulong a) => unchecked((ulong)~(long)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int64_abs(ulong a) => unchecked((long)a < 0 ? 0UL - a : a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int64_dec_eq(ulong a1, ulong a2) => unchecked((long)a1 == (long)a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int64_dec_lt(ulong a1, ulong a2) => unchecked((long)a1 < (long)a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int64_dec_le(ulong a1, ulong a2) => unchecked((long)a1 <= (long)a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_int64_to_int8(ulong a) => unchecked((byte)(sbyte)(long)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_int64_to_int16(ulong a) => unchecked((ushort)(short)(long)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_int64_to_int32(ulong a) => unchecked((uint)(int)(long)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_int64_to_isize(ulong a) => unchecked((ulong)(long)(long)a);

    // ------------------------------------------------------------------ isize

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static long lean_isize_of_big_int(Obj a) => unchecked((long)NumbersInternal.Mod64(lean_nat_to_big(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_isize_of_int(Obj a) => unchecked((ulong)(lean_is_scalar(a) ? (long)lean_scalar_to_int64(a) : lean_isize_of_big_int(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_isize_of_nat(Obj a) => unchecked((ulong)(lean_is_scalar(a) ? (long)lean_unbox(a) : lean_isize_of_big_int(a)));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Obj lean_isize_to_int(ulong a) => unchecked(lean_int64_to_int((long)a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_isize_neg(ulong a) => unchecked((ulong)(0UL - a));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_isize_add(ulong a1, ulong a2) => unchecked((ulong)(a1 + a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_isize_sub(ulong a1, ulong a2) => unchecked((ulong)(a1 - a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_isize_mul(ulong a1, ulong a2) => unchecked((ulong)(a1 * a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_isize_div(ulong a1, ulong a2)
    {
        unchecked
        {
            long lhs = (long)a1;
            long rhs = (long)a2;
            if (rhs == 0) return 0;
            if (lhs == long.MinValue && rhs == -1) return (ulong)long.MinValue;
            return (ulong)(lhs / rhs);
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_isize_mod(ulong a1, ulong a2)
    {
        unchecked
        {
            long lhs = (long)a1;
            long rhs = (long)a2;
            if (rhs == 0) return (ulong)lhs;
            if (lhs == long.MinValue && rhs == -1) return 0;
            return (ulong)(lhs % rhs);
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_isize_land(ulong a1, ulong a2) => unchecked((ulong)((long)a1 & (long)a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_isize_lor(ulong a1, ulong a2) => unchecked((ulong)((long)a1 | (long)a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_isize_xor(ulong a1, ulong a2) => unchecked((ulong)((long)a1 ^ (long)a2));
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_isize_shift_right(ulong a1, ulong a2)
    {
        unchecked
        {
            long lhs = (long)a1;
            long rhs = (((long)a2 % 64) + 64) % 64; // smod 64
            return (ulong)(lhs >> (int)rhs);
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_isize_shift_left(ulong a1, ulong a2)
    {
        unchecked
        {
            long rhs = (((long)a2 % 64) + 64) % 64; // smod 64
            return a1 << (int)rhs;
        }
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_isize_complement(ulong a) => unchecked((ulong)~(long)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_isize_abs(ulong a) => unchecked((long)a < 0 ? 0UL - a : a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_isize_dec_eq(ulong a1, ulong a2) => unchecked((long)a1 == (long)a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_isize_dec_lt(ulong a1, ulong a2) => unchecked((long)a1 < (long)a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_isize_dec_le(ulong a1, ulong a2) => unchecked((long)a1 <= (long)a2 ? (byte)1 : (byte)0);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_isize_to_int8(ulong a) => unchecked((byte)(sbyte)(long)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_isize_to_int16(ulong a) => unchecked((ushort)(short)(long)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_isize_to_int32(ulong a) => unchecked((uint)(int)(long)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_isize_to_int64(ulong a) => unchecked((ulong)(long)(long)a);

    // ------------------------------------------------------------------ Bool

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_bool_to_uint8(byte a) => unchecked((byte)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_bool_to_uint16(byte a) => unchecked((ushort)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_bool_to_uint32(byte a) => unchecked((uint)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_bool_to_uint64(byte a) => unchecked((ulong)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_bool_to_usize(byte a) => unchecked((ulong)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static byte lean_bool_to_int8(byte a) => unchecked((byte)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ushort lean_bool_to_int16(byte a) => unchecked((ushort)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static uint lean_bool_to_int32(byte a) => unchecked((uint)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_bool_to_int64(byte a) => unchecked((ulong)a);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static ulong lean_bool_to_isize(byte a) => unchecked((ulong)a);
}
