<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.IO.DisableFileLocking" Value="true" />
    <ProjectReference Include="../../src/LeanSharp/LeanSharp.csproj" />
  </ItemGroup>
</Project>
