<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>LeanSharp.Cli</AssemblyName>
    <RootNamespace>LeanSharp.Cli</RootNamespace>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <TieredPGO>true</TieredPGO>
  </PropertyGroup>
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.IO.DisableFileLocking" Value="true" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../LeanSharp/LeanSharp.csproj" />
  </ItemGroup>
</Project>
