<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RootNamespace>KernelCheck</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/LeanSharp.Runtime/**/*.cs" Exclude="../../src/LeanSharp.Runtime/bin/**;../../src/LeanSharp.Runtime/obj/**" />
    <Compile Include="*.cs" />
    <None Include="expected_inductives.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="expected_inductives2.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
