<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/LeanSharp.Runtime/Core/**/*.cs" />
    <Compile Include="../../src/LeanSharp.Runtime/Strings/**/*.cs" />
    <Compile Include="Program.cs" />
    <Compile Include="SigCheck.cs" />
  </ItemGroup>
</Project>
