// Generated: checks that every extern of docs/externs-strings_arrays.txt exists with the exact signature.
using LeanSharp.Runtime;
static unsafe class SigCheck {
  public static int Run() {
    int n = 0;
    delegate*<Obj, Obj, Obj> f0 = &LeanRt.lean_array_fget; if (f0 != null) n++;
    delegate*<Obj, Obj, Obj> f1 = &LeanRt.lean_array_fget_borrowed; if (f1 != null) n++;
    delegate*<Obj, Obj, Obj, Obj> f2 = &LeanRt.lean_array_fset; if (f2 != null) n++;
    delegate*<Obj, Obj, Obj, Obj> f3 = &LeanRt.lean_array_fswap; if (f3 != null) n++;
    delegate*<Obj, Obj, Obj, Obj> f4 = &LeanRt.lean_array_get; if (f4 != null) n++;
    delegate*<Obj, Obj, Obj, Obj> f5 = &LeanRt.lean_array_get_borrowed; if (f5 != null) n++;
    delegate*<Obj, Obj> f6 = &LeanRt.lean_array_get_size; if (f6 != null) n++;
    delegate*<Obj, Obj> f7 = &LeanRt.lean_array_mark_linear; if (f7 != null) n++;
    delegate*<Obj, Obj> f8 = &LeanRt.lean_array_mk; if (f8 != null) n++;
    delegate*<Obj, Obj> f9 = &LeanRt.lean_array_pop; if (f9 != null) n++;
    delegate*<Obj, Obj, Obj> f10 = &LeanRt.lean_array_propagate_mark; if (f10 != null) n++;
    delegate*<Obj, Obj, Obj> f11 = &LeanRt.lean_array_push; if (f11 != null) n++;
    delegate*<Obj, Obj, Obj, Obj> f12 = &LeanRt.lean_array_set; if (f12 != null) n++;
    delegate*<Obj, Obj, Obj, Obj> f13 = &LeanRt.lean_array_swap; if (f13 != null) n++;
    delegate*<Obj, Obj> f14 = &LeanRt.lean_array_to_list; if (f14 != null) n++;
    delegate*<Obj, ulong, Obj> f15 = &LeanRt.lean_array_uget; if (f15 != null) n++;
    delegate*<Obj, ulong, Obj> f16 = &LeanRt.lean_array_uget_borrowed; if (f16 != null) n++;
    delegate*<Obj, ulong, Obj, Obj> f17 = &LeanRt.lean_array_uset; if (f17 != null) n++;
    delegate*<Obj, Obj, Obj, Obj, Obj, byte, Obj> f18 = &LeanRt.lean_byte_array_copy_slice; if (f18 != null) n++;
    delegate*<Obj, Obj> f19 = &LeanRt.lean_byte_array_data; if (f19 != null) n++;
    delegate*<Obj, Obj, byte, Obj> f20 = &LeanRt.lean_byte_array_fset; if (f20 != null) n++;
    delegate*<Obj, Obj> f21 = &LeanRt.lean_byte_array_mk; if (f21 != null) n++;
    delegate*<Obj, byte, Obj> f22 = &LeanRt.lean_byte_array_push; if (f22 != null) n++;
    delegate*<Obj, Obj, byte, Obj> f23 = &LeanRt.lean_byte_array_set; if (f23 != null) n++;
    delegate*<Obj, Obj> f24 = &LeanRt.lean_byte_array_size; if (f24 != null) n++;
    delegate*<Obj, ulong, byte, Obj> f25 = &LeanRt.lean_byte_array_uset; if (f25 != null) n++;
    delegate*<Obj, Obj> f26 = &LeanRt.lean_decode_lossy_utf8; if (f26 != null) n++;
    delegate*<Obj, Obj, Obj> f27 = &LeanRt.lean_mk_array; if (f27 != null) n++;
    delegate*<Obj, Obj> f28 = &LeanRt.lean_mk_empty_array_with_capacity; if (f28 != null) n++;
    delegate*<Obj, Obj> f29 = &LeanRt.lean_mk_empty_byte_array; if (f29 != null) n++;
    delegate*<Obj, Obj> f30 = &LeanRt.lean_mk_empty_float_array; if (f30 != null) n++;
    delegate*<Obj, Obj> f31 = &LeanRt.lean_sarray_mark_linear; if (f31 != null) n++;
    delegate*<Obj, Obj, Obj> f32 = &LeanRt.lean_sarray_propagate_mark; if (f32 != null) n++;
    delegate*<Obj, Obj> f33 = &LeanRt.lean_sharecommon_quick; if (f33 != null) n++;
    delegate*<Obj, Obj, Obj, Obj> f34 = &LeanRt.lean_state_sharecommon; if (f34 != null) n++;
    delegate*<Obj, Obj, Obj> f35 = &LeanRt.lean_string_append; if (f35 != null) n++;
    delegate*<Obj, Obj> f36 = &LeanRt.lean_string_data; if (f36 != null) n++;
    delegate*<Obj, Obj> f37 = &LeanRt.lean_string_from_utf8_unchecked; if (f37 != null) n++;
    delegate*<Obj, Obj> f38 = &LeanRt.lean_string_length; if (f38 != null) n++;
    delegate*<Obj, Obj> f39 = &LeanRt.lean_string_mark_linear; if (f39 != null) n++;
    delegate*<Obj, Obj> f40 = &LeanRt.lean_string_mk; if (f40 != null) n++;
    delegate*<ulong, Obj> f41 = &LeanRt.lean_string_of_usize; if (f41 != null) n++;
    delegate*<Obj, Obj, Obj> f42 = &LeanRt.lean_string_propagate_mark; if (f42 != null) n++;
    delegate*<Obj, uint, Obj> f43 = &LeanRt.lean_string_push; if (f43 != null) n++;
    delegate*<Obj, Obj> f44 = &LeanRt.lean_string_to_utf8; if (f44 != null) n++;
    delegate*<Obj, Obj> f45 = &LeanRt.lean_string_utf8_byte_size; if (f45 != null) n++;
    delegate*<Obj, Obj, Obj, Obj> f46 = &LeanRt.lean_string_utf8_extract; if (f46 != null) n++;
    delegate*<Obj, Obj, Obj, Obj> f47 = &LeanRt.lean_string_utf8_extract_fast; if (f47 != null) n++;
    delegate*<Obj, Obj, Obj> f48 = &LeanRt.lean_string_utf8_get_opt; if (f48 != null) n++;
    delegate*<Obj, Obj, Obj> f49 = &LeanRt.lean_string_utf8_next; if (f49 != null) n++;
    delegate*<Obj, Obj, Obj> f50 = &LeanRt.lean_string_utf8_next_fast; if (f50 != null) n++;
    delegate*<Obj, Obj, Obj> f51 = &LeanRt.lean_string_utf8_prev; if (f51 != null) n++;
    delegate*<Obj, Obj, uint, Obj> f52 = &LeanRt.lean_string_utf8_set; if (f52 != null) n++;
    delegate*<Obj, Obj, byte> f53 = &LeanRt.lean_byte_array_fget; if (f53 != null) n++;
    delegate*<Obj, Obj, byte> f54 = &LeanRt.lean_byte_array_get; if (f54 != null) n++;
    delegate*<Obj, ulong, byte> f55 = &LeanRt.lean_byte_array_uget; if (f55 != null) n++;
    delegate*<Obj, Obj, byte> f56 = &LeanRt.lean_byteslice_beq; if (f56 != null) n++;
    delegate*<Obj, Obj, byte> f57 = &LeanRt.lean_name_eq; if (f57 != null) n++;
    delegate*<Obj, Obj, byte> f58 = &LeanRt.lean_sarray_dec_eq; if (f58 != null) n++;
    delegate*<Obj, Obj, byte> f59 = &LeanRt.lean_sharecommon_eq; if (f59 != null) n++;
    delegate*<Obj, Obj, byte> f60 = &LeanRt.lean_slice_dec_lt; if (f60 != null) n++;
    delegate*<Obj, Obj, byte> f61 = &LeanRt.lean_string_compare; if (f61 != null) n++;
    delegate*<Obj, Obj, byte> f62 = &LeanRt.lean_string_dec_eq; if (f62 != null) n++;
    delegate*<Obj, Obj, byte> f63 = &LeanRt.lean_string_dec_lt; if (f63 != null) n++;
    delegate*<Obj, Obj, byte> f64 = &LeanRt.lean_string_get_byte_fast; if (f64 != null) n++;
    delegate*<Obj, Obj, byte> f65 = &LeanRt.lean_string_is_valid_pos; if (f65 != null) n++;
    delegate*<Obj, Obj, Obj, Obj, Obj, byte> f66 = &LeanRt.lean_string_memcmp; if (f66 != null) n++;
    delegate*<Obj, ulong, byte> f67 = &LeanRt.lean_string_uget_byte_fast; if (f67 != null) n++;
    delegate*<Obj, Obj, byte> f68 = &LeanRt.lean_string_utf8_at_end; if (f68 != null) n++;
    delegate*<Obj, byte> f69 = &LeanRt.lean_string_validate_utf8; if (f69 != null) n++;
    delegate*<Obj, Obj, uint> f70 = &LeanRt.lean_string_utf8_get; if (f70 != null) n++;
    delegate*<Obj, Obj, uint> f71 = &LeanRt.lean_string_utf8_get_bang; if (f71 != null) n++;
    delegate*<Obj, Obj, uint> f72 = &LeanRt.lean_string_utf8_get_fast; if (f72 != null) n++;
    delegate*<Obj, ulong> f73 = &LeanRt.lean_array_size; if (f73 != null) n++;
    delegate*<Obj, ulong> f74 = &LeanRt.lean_byte_array_hash; if (f74 != null) n++;
    delegate*<Obj, ulong> f75 = &LeanRt.lean_sarray_size; if (f75 != null) n++;
    delegate*<Obj, ulong> f76 = &LeanRt.lean_sharecommon_hash; if (f76 != null) n++;
    delegate*<Obj, ulong> f77 = &LeanRt.lean_slice_hash; if (f77 != null) n++;
    delegate*<Obj, ulong> f78 = &LeanRt.lean_string_hash; if (f78 != null) n++;
    return n;
  }
}
