/-
LeanSharp: emit C# source code from Lean's compiled IR (λRC).

This tool is only used at development time to (re)generate the C# translation of the Lean
standard library and compiler (`Init`, `Std`, `Lean`, `Lake`). The generated C# is pure managed
code that runs on top of `LeanSharp.Runtime`.

It is a port of the (pre-LCNF) `Lean.Compiler.IR.EmitC` backend. Module initialization order is
taken from the C files generated by the regular Lean build (`build/.../lib/temp/**/*.c`), since the
original declaration order is not stored in `.ir` files.

Usage:
  lean --run EmitCSharp.lean <sysroot> <cdir> <outdir> <RootModule>...
-/
import Lean
open Lean IR

namespace EmitCS

def closureMax : Nat := 16

def isBoxedName (name : Name) : Bool :=
  name matches .str _ "_boxed"

def ensureHasDefault (alts : Array Alt) : Array Alt :=
  if alts.any Alt.isDefault then alts
  else
    let last := alts.back!
    let alts := alts.pop
    alts.push (Alt.default last.body)

structure Ctx where
  env        : Environment
  owners     : Std.HashMap String String  -- C symbol → C# class
  modName    : Name
  className  : String
  eager      : Std.HashSet String := {}   -- constants initialized eagerly by module init
  jpMap      : JPParamsMap := {}
  mainFn     : FunId := default
  mainParams : Array Param := #[]
  declIdx    : Std.HashMap Name Nat := {}  -- position of each function in the module

abbrev M := ReaderT Ctx (EStateM String String)

@[inline] def getEnv : M Environment := Ctx.env <$> read

@[inline] def emit {α : Type} [ToString α] (a : α) : M Unit :=
  modify fun out => out ++ toString a

@[inline] def emitLn {α : Type} [ToString α] (a : α) : M Unit := do
  emit a; emit "\n"

def emitLns {α : Type} [ToString α] (as : List α) : M Unit :=
  as.forM fun a => emitLn a

def getDecl (n : Name) : M Decl := do
  match findEnvDecl (← getEnv) n with
  | some d => pure d
  | none   => throw s!"unknown declaration '{n}'"

def argToCS (x : Arg) : String :=
  match x with
  | .var x => toString x
  | .erased => "lean_box(0)"

def emitArg (x : Arg) : M Unit := emit (argToCS x)

def toCSType : IRType → String
  | .float      => "double"
  | .float32    => "float"
  | .uint8      => "byte"
  | .uint16     => "ushort"
  | .uint32     => "uint"
  | .uint64     => "ulong"
  | .usize      => "ulong"
  | .object     => "Obj"
  | .tagged     => "Obj"
  | .tobject    => "Obj"
  | .erased     => "Obj"
  | .void       => "Obj"
  | .struct _ _ => panic! "not implemented yet"
  | .union _ _  => panic! "not implemented yet"

def defaultValue : IRType → String
  | .float => "0.0"
  | .float32 => "0.0f"
  | .uint8 | .uint16 | .uint32 | .uint64 | .usize => "0"
  | _ => "null"

def hex (n : Nat) : String :=
  let s := String.ofList (Nat.toDigits 16 n)
  "".pushn '0' (4 - s.length) ++ s

/-- C# string literal (UTF-16 source; encoded to UTF-8 by the `u8` suffix). -/
def quoteString (s : String) : String :=
  let q := s.foldl
    (fun q c => q ++
      if c == '\n' then "\\n"
      else if c == '\r' then "\\r"
      else if c == '\t' then "\\t"
      else if c == '\\' then "\\\\"
      else if c == '\"' then "\\\""
      else if c.toNat <= 31 || c.toNat == 127 then "\\u" ++ hex c.toNat
      else if c.toNat == 0x2028 || c.toNat == 0x2029 || c.toNat == 0x85 then "\\u" ++ hex c.toNat
      else if c.toNat > 0xFFFF then
        let v := c.toNat - 0x10000
        "\\u" ++ hex (0xD800 + v / 0x400) ++ "\\u" ++ hex (0xDC00 + v % 0x400)
      else String.singleton c)
    "\""
  q ++ "\""

/-- .NET metadata names are limited to 1024 bytes: shorten very long symbols deterministically. -/
def shortName (c : String) : String :=
  if c.length > 480 then
    (c.take 400).copy ++ "_H" ++ (String.ofList (Nat.toDigits 16 (hash c).toNat))
  else c

/-- Shorten all long identifiers in a line of C code. -/
def shortenIdents (l : String) : String := Id.run do
  if l.length ≤ 480 then return l
  let mut out := ""
  let mut tok := ""
  for c in l.toList do
    if c.isAlphanum || c == '_' then
      tok := tok.push c
    else
      out := out ++ shortName tok
      tok := ""
      out := out.push c
  return out ++ shortName tok

def toCName (n : Name) : M String := do
  let env ← getEnv
  match getExportNameFor? env n with
  | some (.str .anonymous s) => return s
  | some _                   => throw s!"invalid export name '{n}'"
  | none                     => return shortName (if n == `main then "_lean_main" else getSymbolStem env n)

/-- Qualified reference to the C# member implementing the C symbol `c`. -/
def qualify (c : String) : M String := do
  let ctx ← read
  match ctx.owners[c]? with
  | some cls => if cls == ctx.className then return c else return s!"{cls}.{c}"
  | none => return c  -- runtime function (`using static LeanSharp.Runtime.LeanRt`)

def emitCName (n : Name) : M Unit := do emit (← qualify (← toCName n))

def ctorScalarSizeStr (usize : Nat) (ssize : Nat) : String :=
  toString (8 * usize + ssize)

def declareVar (x : VarId) (t : IRType) : M Unit := do
  emit (toCSType t); emit " "; emit x; emit " = "; emit (defaultValue t); emit "; "

def declareParams (ps : Array Param) : M Unit :=
  ps.forM fun p => declareVar p.x p.ty

def isTailCallTo' (mainFn : FunId) (b : FnBody) : Bool :=
  match b with
  | .vdecl x _ (.fap f _) (.ret (.var y)) => x == y && f == mainFn
  | _ => false

partial def declareVars : FnBody → Bool → M Bool
  | e@(.vdecl x t _ b), d => do
    let ctx ← read
    if isTailCallTo' ctx.mainFn e then
      pure d
    else
      declareVar x t; declareVars b true
  | .jdecl _ xs _ b,    d => do declareParams xs; declareVars b (d || xs.size > 0)
  | e,                  d => if e.isTerminal then pure d else declareVars e.body d

def emitTag (x : VarId) (xType : IRType) : M Unit := do
  if xType.isObj then do
    emit "lean_obj_tag("; emit x; emit ")"
  else
    emit x

def isIf (alts : Array Alt) : Option (Nat × FnBody × FnBody) :=
  if h : alts.size ≠ 2 then none
  else match alts[0] with
    | Alt.ctor c b => some (c.cidx, b, alts[1].body)
    | _            => none

def emitInc (x : VarId) (n : Nat) (checkRef : Bool) : M Unit := do
  emit <|
    if checkRef then (if n == 1 then "lean_inc" else "lean_inc_n")
    else (if n == 1 then "lean_inc_ref" else "lean_inc_ref_n")
  emit "("; emit x
  if n != 1 then emit ", "; emit n
  emitLn ");"

def emitDec (x : VarId) (n : Nat) (checkRef : Bool) : M Unit := do
  emit (if checkRef then "lean_dec" else "lean_dec_ref")
  emit "("; emit x
  if n != 1 then emit ", "; emit n
  emitLn ");"

def emitDel (x : VarId) : M Unit := do
  emit "lean_del_object("; emit x; emitLn ");"

def emitSetTag (x : VarId) (i : Nat) : M Unit := do
  emit "lean_ctor_set_tag("; emit x; emit ", "; emit i; emitLn ");"

def emitSet (x : VarId) (i : Nat) (y : Arg) : M Unit := do
  emit "lean_ctor_set("; emit x; emit ", "; emit i; emit ", "; emitArg y; emitLn ");"

def emitUSet (x : VarId) (n : Nat) (y : VarId) : M Unit := do
  emit "lean_ctor_set_usize("; emit x; emit ", "; emit n; emit ", "; emit y; emitLn ");"

/-- Scalar fields are accessed as in C: the offset `sizeof(void*)*n + offset` counts from the first
field, where `n` is the number of object fields *plus the number of `USize` fields* (which precede
the other scalars). The runtime subtracts the object fields. (Passing only `offset` is wrong for
structures that have both `USize` and smaller scalar fields.) -/
def emitSSet (x : VarId) (n : Nat) (offset : Nat) (y : VarId) (t : IRType) : M Unit := do
  match t with
  | .float   => emit "lean_ctor_set_float"
  | .float32 => emit "lean_ctor_set_float32"
  | .uint8   => emit "lean_ctor_set_uint8"
  | .uint16  => emit "lean_ctor_set_uint16"
  | .uint32  => emit "lean_ctor_set_uint32"
  | .uint64  => emit "lean_ctor_set_uint64"
  | _        => throw "invalid instruction"
  emit "("; emit x; emit ", "; emit (8 * n + offset); emit ", "; emit y; emitLn ");"

def getJPParams (j : JoinPointId) : M (Array Param) := do
  match (← read).jpMap[j]? with
  | some ps => pure ps
  | none    => throw "unknown join point"

def emitJmp (j : JoinPointId) (xs : Array Arg) : M Unit := do
  let ps ← getJPParams j
  if h : xs.size = ps.size then
    xs.size.forM fun i _ => do
      let p := ps[i]
      let x := xs[i]
      emit p.x; emit " = "; emitArg x; emitLn ";"
    emit "goto "; emit j; emitLn ";"
  else
    throw "invalid goto"

def emitLhs (z : VarId) : M Unit := do
  emit z; emit " = "

def emitArgs (ys : Array Arg) : M Unit :=
  ys.size.forM fun i _ => do
    if i > 0 then emit ", "
    emitArg ys[i]

def emitAllocCtor (c : CtorInfo) : M Unit := do
  emit "lean_alloc_ctor("; emit c.cidx; emit ", "; emit c.size; emit ", "
  emit (ctorScalarSizeStr c.usize c.ssize); emitLn ");"

def emitCtorSetArgs (z : VarId) (ys : Array Arg) : M Unit :=
  ys.size.forM fun i _ => do
    emit "lean_ctor_set("; emit z; emit ", "; emit i; emit ", "; emitArg ys[i]; emitLn ");"

def emitCtor (z : VarId) (c : CtorInfo) (ys : Array Arg) : M Unit := do
  emitLhs z
  if c.size == 0 && c.usize == 0 && c.ssize == 0 then do
    emit "lean_box("; emit c.cidx; emitLn ");"
  else do
    emitAllocCtor c; emitCtorSetArgs z ys

def emitReset (z : VarId) (n : Nat) (x : VarId) : M Unit := do
  emit "if (lean_is_exclusive("; emit x; emitLn ")) {"
  n.forM fun i _ => do
    emit " lean_ctor_release("; emit x; emit ", "; emit i; emitLn ");"
  emit " "; emitLhs z; emit x; emitLn ";"
  emitLn "} else {"
  emit " lean_dec_ref("; emit x; emitLn ");"
  emit " "; emitLhs z; emitLn "lean_box(0);"
  emitLn "}"

def emitReuse (z : VarId) (x : VarId) (c : CtorInfo) (updtHeader : Bool) (ys : Array Arg) : M Unit := do
  -- `lean_ctor_reuse` allocates a fresh object if `x` is a scalar or has an incompatible layout
  emitLhs z; emit "lean_ctor_reuse("; emit x; emit ", "; emit c.cidx; emit ", "; emit c.size; emit ", "
  emit (ctorScalarSizeStr c.usize c.ssize); emit ", "; emit (if updtHeader then "true" else "false"); emitLn ");"
  emitCtorSetArgs z ys

def emitProj (z : VarId) (i : Nat) (x : VarId) : M Unit := do
  emitLhs z; emit "lean_ctor_get("; emit x; emit ", "; emit i; emitLn ");"

def emitUProj (z : VarId) (i : Nat) (x : VarId) : M Unit := do
  emitLhs z; emit "lean_ctor_get_usize("; emit x; emit ", "; emit i; emitLn ");"

def emitSProj (z : VarId) (t : IRType) (n offset : Nat) (x : VarId) : M Unit := do
  emitLhs z
  match t with
  | .float    => emit "lean_ctor_get_float"
  | .float32  => emit "lean_ctor_get_float32"
  | .uint8    => emit "lean_ctor_get_uint8"
  | .uint16   => emit "lean_ctor_get_uint16"
  | .uint32   => emit "lean_ctor_get_uint32"
  | .uint64   => emit "lean_ctor_get_uint64"
  | _         => throw "invalid instruction"
  emit "("; emit x; emit ", "; emit (8 * n + offset); emitLn ");"

def toStringArgs (ys : Array Arg) : List String :=
  ys.toList.map argToCS

/-- Cast needed when assigning the result of a runtime call returning `ulong`/`uint`/`bool`-like
values to a variable of type `t`. We always emit an explicit cast for small integer types. -/
def castFor (t : IRType) : String :=
  match t with
  | .uint8 => "(byte)"
  | .uint16 => "(ushort)"
  | .uint32 => "(uint)"
  | .uint64 | .usize => "(ulong)"
  | .float => "(double)"
  | .float32 => "(float)"
  | _ => ""

def castOpen (t : IRType) : String :=
  match t with
  | .uint8 => "lean_u8("
  | _ => castFor t ++ "("

def emitSimpleExternalCall (t : IRType) (f : String) (ps : Array Param) (ys : Array Arg) : M Unit := do
  emit (castOpen t)
  emit (← qualify f); emit "("
  discard <| ys.size.foldM
    (fun i _ (first : Bool) =>
      let ty := ps[i]!.ty
      if ty.isErased || ty.isVoid then
        pure first
      else do
        unless first do emit ", "
        emitArg ys[i]
        pure false)
    true
  emitLn "));"

def emitExternCall (t : IRType) (f : FunId) (ps : Array Param) (extData : ExternAttrData) (ys : Array Arg) : M Unit :=
  match getExternEntryFor extData `c with
  | some (ExternEntry.standard _ extFn) => emitSimpleExternalCall t extFn ps ys
  | some (ExternEntry.inline _ pat)     => do
    emit (castOpen t); emit (expandExternPattern pat (toStringArgs ys)); emitLn ");"
  | some (ExternEntry.adhoc _) => do
    let n ← toCName f
    emitSimpleExternalCall t n ps ys
  | _ => throw s!"failed to emit extern application '{f}'"

def emitFullApp (z : VarId) (t : IRType) (f : FunId) (ys : Array Arg) : M Unit := do
  emitLhs z
  let decl ← getDecl f
  match decl with
  | .fdecl (xs := ps) .. | .extern (xs := ps) (ext := { entries := [.opaque], .. }) .. =>
    emitCName f
    if ps.size > 0 then
      let (ys, _) := ys.zip ps |>.filter (fun (_, p) => !p.ty.isVoid) |>.unzip
      if ps.size > closureMax && isBoxedName f then
        emit "(new Obj[] {"; emitArgs ys; emit "})"
      else
        emit "("; emitArgs ys; emit ")"
    emitLn ";"
  | .extern _ ps _ extData => emitExternCall t f ps extData ys

def fnPtrType (arity : Nat) (boxedArray : Bool) : String :=
  if boxedArray then "delegate*<Obj[], Obj>"
  else
    let args := String.intercalate ", " (List.replicate (arity + 1) "Obj")
    s!"delegate*<{args}>"

def emitPartialApp (z : VarId) (f : FunId) (ys : Array Arg) : M Unit := do
  let decl ← getDecl f
  let arity := decl.params.size
  let big := arity > closureMax && isBoxedName f
  emitLhs z; emit "lean_alloc_closure(("; emit (fnPtrType arity big); emit ")&"; emitCName f
  emit ", "; emit arity; emit ", "; emit ys.size; emitLn ");"
  ys.size.forM fun i _ => do
    let y := ys[i]
    emit "lean_closure_set("; emit z; emit ", "; emit i; emit ", "; emitArg y; emitLn ");"

def emitApp (z : VarId) (f : VarId) (ys : Array Arg) : M Unit :=
  if ys.size > closureMax then do
    emitLhs z; emit "lean_apply_m("; emit f; emit ", "; emit ys.size; emit ", new Obj[] {"; emitArgs ys; emitLn "});"
  else do
    emitLhs z; emit "lean_apply_"; emit ys.size; emit "("; emit f; emit ", "; emitArgs ys; emitLn ");"

def emitBoxFn (xType : IRType) : M Unit :=
  match xType with
  | .usize   => emit "lean_box_usize"
  | .uint32  => emit "lean_box_uint32"
  | .uint64  => emit "lean_box_uint64"
  | .float   => emit "lean_box_float"
  | .float32 => emit "lean_box_float32"
  | _        => emit "lean_box"

def emitBox (z : VarId) (x : VarId) (xType : IRType) : M Unit := do
  emitLhs z; emitBoxFn xType; emit "("; emit x; emitLn ");"

def emitUnbox (z : VarId) (t : IRType) (x : VarId) : M Unit := do
  emitLhs z
  emit (castFor t)
  emit (getUnboxOpName t)
  emit "("; emit x; emitLn ");"

def emitIsShared (z : VarId) (x : VarId) : M Unit := do
  emitLhs z; emit "(byte)(lean_is_exclusive("; emit x; emitLn ") ? 0 : 1);"

def emitNumLit (t : IRType) (v : Nat) : M Unit := do
  if t.isObj then
    if v < UInt32.size then
      emit "lean_unsigned_to_nat("; emit v; emit "u)"
    else
      emit "lean_cstr_to_nat(\""; emit v; emit "\")"
  else
    match t with
    | .uint8 => emit "(byte)"; emit v
    | .uint16 => emit "(ushort)"; emit v
    | .uint32 => emit v; emit "u"
    | .uint64 | .usize => emit v; emit "UL"
    | .float => emit v; emit ".0"
    | .float32 => emit v; emit ".0f"
    | _ => emit v

def emitLit (z : VarId) (t : IRType) (v : LitVal) : M Unit := do
  emitLhs z
  match v with
  | .num v => emitNumLit t v; emitLn ";"
  | .str v =>
    emit "lean_mk_string_unchecked("
    emit (quoteString v); emit "u8, "
    emit v.utf8ByteSize; emit ", "
    emit v.length; emitLn ");"

def emitVDecl (z : VarId) (t : IRType) (v : IR.Expr) : M Unit :=
  match v with
  | .ctor c ys      => emitCtor z c ys
  | .reset n x      => emitReset z n x
  | .reuse x c u ys => emitReuse z x c u ys
  | .proj i x       => emitProj z i x
  | .uproj i x      => emitUProj z i x
  | .sproj n o x    => emitSProj z t n o x
  | .fap c ys       => emitFullApp z t c ys
  | .pap c ys       => emitPartialApp z c ys
  | .ap x ys        => emitApp z x ys
  | .box t x        => emitBox z x t
  | .unbox x        => emitUnbox z t x
  | .isShared x     => emitIsShared z x
  | .lit v          => emitLit z t v

def paramEqArg (p : Param) (x : Arg) : Bool :=
  match x with
  | .var x => p.x == x
  | .erased => false

def overwriteParam (ps : Array Param) (ys : Array Arg) : Bool :=
  let n := ps.size
  n.any fun i _ =>
    let p := ps[i]
    (i+1, n).anyI fun j _ _ => paramEqArg p ys[j]!

def emitTailCall (v : IR.Expr) : M Unit :=
  match v with
  | .fap _ ys => do
    let ctx ← read
    let ps := ctx.mainParams
    if ps.size = ys.size then
      let (ps, ys) := ps.zip ys |>.filter (fun (p, _) => !p.ty.isVoid) |>.unzip
      if overwriteParam ps ys then
        emitLn "{"
        ps.size.forM fun i _ => do
          let p := ps[i]!
          let y := ys[i]!
          unless paramEqArg p y do
            emit (toCSType p.ty); emit " _tmp_"; emit i; emit " = "; emitArg y; emitLn ";"
        ps.size.forM fun i _ => do
          let p := ps[i]!
          let y := ys[i]!
          unless paramEqArg p y do emit p.x; emit " = _tmp_"; emit i; emitLn ";"
        emitLn "}"
      else
        ps.size.forM fun i _ => do
          let p := ps[i]!
          let y := ys[i]!
          unless paramEqArg p y do emit p.x; emit " = "; emitArg y; emitLn ";"
      emitLn "goto _start;"
    else
      throw "invalid tail call"
  | _ => throw "bug at emitTailCall"

mutual

partial def emitIf (x : VarId) (xType : IRType) (tag : Nat) (t : FnBody) (e : FnBody) : M Unit := do
  emit "if ("; emitTag x xType; emit " == "; emit tag; emitLn ")"
  emitFnBody t
  emitLn "else"
  emitFnBody e

partial def emitCase (x : VarId) (xType : IRType) (alts : Array Alt) : M Unit :=
  match isIf alts with
  | some (tag, t, e) => emitIf x xType tag t e
  | _ => do
    emit "switch ("; emitTag x xType; emitLn ") {"
    let alts := ensureHasDefault alts
    alts.forM fun alt => do
      match alt with
      | .ctor c b  => emit "case "; emit c.cidx; emitLn ":"; emitFnBody b
      | .default b => emitLn "default: "; emitFnBody b
    emitLn "}"

partial def emitBlock (b : FnBody) : M Unit := do
  match b with
  | .jdecl _ _  _ b      => emitBlock b
  | d@(.vdecl x t v b)   =>
    let ctx ← read
    if isTailCallTo' ctx.mainFn d then
      emitTailCall v
    else
      emitVDecl x t v
      emitBlock b
  | .inc x n c p b       =>
    unless p do emitInc x n c
    emitBlock b
  | .dec x n c p b       =>
    unless p do emitDec x n c
    emitBlock b
  | .del x b             => emitDel x; emitBlock b
  | .setTag x i b        => emitSetTag x i; emitBlock b
  | .set x i y b         => emitSet x i y; emitBlock b
  | .uset x i y b        => emitUSet x i y; emitBlock b
  | .sset x i o y t b    => emitSSet x i o y t; emitBlock b
  | .ret x               => emit "return "; emitArg x; emitLn ";"
  | .case _ x xType alts => emitCase x xType alts
  | .jmp j xs            => emitJmp j xs
  | .unreachable         => emitLn "throw lean_internal_panic_unreachable();"

partial def emitJPs : FnBody → M Unit
  | .jdecl j _  v b => do emit j; emitLn ":"; emitFnBody v; emitJPs b
  | e               => do unless e.isTerminal do emitJPs e.body

partial def emitFnBody (b : FnBody) : M Unit := do
  emitLn "{"
  let declared ← declareVars b false
  if declared then emitLn ""
  emitBlock b
  emitJPs b
  emitLn "}"

end

/-- The functions called (full applications) in a function body. -/
partial def collectCalls : FnBody → Array FunId → Array FunId
  | .vdecl _ _ (.fap f _) b, acc => collectCalls b (acc.push f)
  | .jdecl _ _ v b, acc          => collectCalls b (collectCalls v acc)
  | .case _ _ _ alts, acc        => alts.foldl (fun acc alt => collectCalls alt.body acc) acc
  | e, acc                       => if e.isTerminal then acc else collectCalls e.body acc

/--
Whether function `f` (with body `b`) gets a stack probe. A recursion among compiled functions
is a cycle in the call graph of one module (imports are acyclic), and every cycle contains a call
from a function to itself or to one that comes later in the module's list of functions; probing
the callers of such calls covers every cycle. (Recursion through closures goes through
`lean_apply_N`, which probes as well.)
-/
def needsStackProbe (f : FunId) (b : FnBody) : M Bool := do
  let idx := (← read).declIdx
  let some i := idx[f]? | return false
  return (collectCalls b #[]).any fun g => match idx[g]? with
    | some j => j >= i
    | none   => false

def emitDeclAux (d : Decl) : M Unit := do
  let (_, jpMap) := mkVarJPMaps d
  withReader (fun ctx => { ctx with jpMap := jpMap }) do
  match d with
  | .fdecl (f := f) (xs := xs) (type := t) (body := b) .. =>
    let baseName ← toCName f
    let ctx ← read
    if xs.size == 0 then
      if ctx.eager.contains baseName then
        -- initialized by the module initializer
        emitLn s!"public static {toCSType t} {baseName};"
        if let .unreachable := b then return
      else
        -- lazily initialized constant (closed terms, ground values, ...)
        let cell := baseName ++ "_cell"
        match t with
        | .object | .tobject | .tagged | .void | .erased =>
          emitLn s!"static Obj {cell};"
          emitLn s!"public static Obj {baseName} => {cell} ?? lean_obj_once(ref {cell}, &_init_{baseName});"
        | _ =>
          let ty := toCSType t
          emitLn s!"static {ty} {cell}; static int {cell}_st;"
          emitLn s!"public static {ty} {baseName} => {cell}_st == 2 ? {cell} : lean_scalar_once(ref {cell}, ref {cell}_st, &_init_{baseName});"
      emit s!"public static {toCSType t} _init_{baseName}()"
    else
      emit "public static "
      emit (toCSType t); emit " "
      let xs := xs.filter (fun p => !p.ty.isVoid)
      emit baseName
      emit "("
      if xs.size > closureMax && isBoxedName d.name then
        emit "Obj[] _args"
      else
        xs.size.forM fun i _ => do
          if i > 0 then emit ", "
          let x := xs[i]
          emit (toCSType x.ty); emit " "; emit x.x
      emit ")"
    emitLn " {"
    let xs := xs.filter (fun p => !p.ty.isVoid)
    if xs.size > closureMax && isBoxedName d.name then
      xs.size.forM fun i _ => do
        let x := xs[i]!
        emit "Obj "; emit x.x; emit " = _args["; emit i; emitLn "];"
    if xs.size > 0 then
      if ← needsStackProbe f b then emitLn "lean_stack_probe();"
    emitLn "_start:"
    withReader (fun ctx => { ctx with mainFn := f, mainParams := d.params }) (emitFnBody b)
    emitLn "}"
  | _ => pure ()

def emitDecl (d : Decl) : M Unit := do
  let d := d.normalizeIds
  try
    emitDeclAux d
  catch err =>
    throw s!"{err}\ncompiling:\n{d}"

/-! ## Module initialization

We translate the bodies of the C initialization functions of the module (generated by the
regular Lean build) since they record the original declaration order. -/

structure InitInfo where
  imports : Array String := #[]   -- C init function names of imported modules
  body    : Array String := #[]   -- statements (C) of the module's own initialization

/-- Extract the body lines of the C function whose definition line starts with `header`. -/
def extractFn (lines : Array String) (header : String) : Option (Array String) := Id.run do
  let mut i := 0
  while i < lines.size do
    if lines[i]!.startsWith header then
      let mut body := #[]
      let mut j := i + 1
      while j < lines.size && lines[j]! != "}" do
        body := body.push lines[j]!
        j := j + 1
      return some body
    i := i + 1
  return none

def isImportInitCall (l : String) : Option String :=
  if l.startsWith "res = " && l.endsWith "(builtin);" then
    some ((l.drop 6).dropEnd 10).copy
  else none

def parseInit (cfile : String) (stem : String) : InitInfo := Id.run do
  let lines := (cfile.splitOn "\n").toArray.map (·.trimAscii.copy)
  let legacy := extractFn lines s!"LEAN_EXPORT lean_object* initialize_{stem}(uint8_t builtin)"
  let rt := extractFn lines s!"LEAN_EXPORT lean_object* runtime_initialize_{stem}(uint8_t builtin)"
  let metaFn := extractFn lines s!"LEAN_EXPORT lean_object* meta_initialize_{stem}(uint8_t builtin)"
  let mut info : InitInfo := {}
  match rt, metaFn, legacy with
  | some rt, some metaFn, some legacy =>
    for l in legacy do
      if let some fn := isImportInitCall l then
        if fn.startsWith "initialize_" then
          info := { info with imports := info.imports.push fn }
    for l in rt ++ metaFn do
      if (isImportInitCall l).isNone then
        info := { info with body := info.body.push l }
  | _, _, some legacy =>
    for l in legacy do
      if let some fn := isImportInitCall l then
        info := { info with imports := info.imports.push fn }
      else
        info := { info with body := info.body.push l }
  | _, _, none => pure ()
  -- drop the error checks that belonged to the (removed) import calls
  let mut body := #[]
  let mut skipNext := false
  let mut prevWasImport := false
  for l in info.body do
    if l == "if (lean_io_result_is_error(res)) return res;" && prevWasImport then
      prevWasImport := false
      continue
    prevWasImport := false
    body := body.push l
  let _ := skipNext
  return { info with body }

/-- C symbols assigned by a module initializer (i.e. eagerly initialized constants). -/
def eagerNames (info : InitInfo) : Std.HashSet String := Id.run do
  let mut s := {}
  for l in info.body do
    match l.splitOn " = " with
    | [lhs, _] => if lhs != "res" then s := s.insert lhs
    | _ => pure ()
  return s

def translateInitLine (l : String) (types : Std.HashMap String IRType) : M (Option String) := do
  let l := shortenIdents l
  if l.isEmpty then return none
  if l == "lean_object * res;" then return none
  if l.startsWith "if (_G_" then return none
  if l.startsWith "_G_" then return none
  if l == "lean_initialize_runtime_module();" || l == "lean_initialize();" then return none
  if l == "if (lean_io_result_is_error(res)) return res;" then return some l
  if l == "lean_dec_ref(res);" then return some l
  if l.startsWith "return " then return none
  if l.startsWith "res = " then
    let rhs := (l.drop 6).copy
    match rhs.splitOn "(" with
    | fn :: _ => return some s!"res = {← qualify fn}{(rhs.drop fn.length).copy}"
    | _ => throw s!"cannot parse init line: {l}"
  if l.startsWith "lean_mark_persistent(" then
    let n := ((l.drop "lean_mark_persistent(".length).dropEnd 2).copy
    return if types.contains n then some l else none
  match l.splitOn " = " with
  | [lhs, rhs] =>
    if !types.contains lhs then return some s!"/* skipped (not in IR): {l} */"
    if rhs.startsWith "_init_" then
      return some s!"{lhs} = {rhs}"
    else if rhs == "lean_io_result_get_value(res);" then
      return some l
    else if rhs.startsWith "lean_unbox" then
      let t := types[lhs]?.getD .object
      return some s!"{lhs} = {castFor t}{rhs}"
    else throw s!"cannot parse init line: {l}"
  | _ => throw s!"cannot parse init line: {l}"

def emitInitFn (info : InitInfo) (initClass : Std.HashMap String String) (types : Std.HashMap String IRType) : M Unit := do
  emitLns [
    "static bool _G_initialized;",
    "public static Obj initialize(byte builtin) {",
    "Obj res;",
    "if (_G_initialized) return lean_io_result_mk_ok(lean_box(0));",
    "_G_initialized = true;"
  ]
  for fn in info.imports do
    match initClass[fn]? with
    | some cls =>
      emitLn s!"res = {cls}.initialize(builtin);"
      emitLn "if (lean_io_result_is_error(res)) return res;"
      emitLn "lean_dec_ref(res);"
    | none => emitLn s!"/* unknown import initializer {fn} */"
  for l in info.body do
    if let some l ← translateInitLine l types then
      emitLn l
  emitLns ["return lean_io_result_mk_ok(lean_box(0));", "}"]

def emitMainFnIfNeeded (decls : Array Decl) : M Unit := do
  let some d := decls.find? (·.name == `main) | return
  let .fdecl (xs := xs) .. := d | return
  let env ← getEnv
  let retTy := env.find? `main |>.get! |>.type |>.getForallBody
  let retTy := retTy.appArg!
  let hasExitCode := retTy.constName? == some ``UInt32
  emitLn "public static int main(string[] args) {"
  emitLn "Obj res = initialize(1);"
  emitLn "lean_io_mark_end_initialization();"
  emitLn "if (lean_io_result_is_ok(res)) {"
  emitLn "lean_dec_ref(res);"
  emitLn "lean_init_task_manager();"
  if xs.size == 2 then
    emitLn "Obj inp = lean_box(0);"
    emitLn "for (int i = args.Length - 1; i >= 0; i--) { Obj n = lean_alloc_ctor(1,2,0); lean_ctor_set(n, 0, lean_mk_string(args[i])); lean_ctor_set(n, 1, inp); inp = n; }"
    emitLn "res = _lean_main(inp);"
  else
    emitLn "res = _lean_main();"
  emitLn "}"
  emitLn "lean_finalize_task_manager();"
  emitLn "if (lean_io_result_is_ok(res)) {"
  emitLn (if hasExitCode then "int ret = (int)lean_unbox_uint32(lean_io_result_get_value(res));" else "int ret = 0;")
  emitLn "lean_dec_ref(res); return ret;"
  emitLn "} else { lean_io_result_show_error(res); lean_dec_ref(res); return 1; }"
  emitLn "}"

def exportFnType (xs : Array Param) (ty : IRType) : String :=
  let xs := xs.filter (fun p => !p.ty.isVoid)
  let ts := xs.toList.map (fun p => toCSType p.ty) ++ [toCSType ty]
  "delegate*<" ++ String.intercalate ", " ts ++ ">"

def mangleModName (m : Name) : String :=
  "M_" ++ m.mangle ""

def emitModule (decls : Array Decl) (info : InitInfo) (initClass : Std.HashMap String String) : M Unit := do
  let ctx ← read
  emitLn "// <auto-generated/>"
  emitLn s!"// Lean module: {ctx.modName}"
  emitLns [
    "#pragma warning disable",
    "#nullable disable",
    "using LeanSharp.Runtime;",
    "using static LeanSharp.Runtime.LeanRt;",
    "namespace LeanSharp.Compiled;",
    s!"public static unsafe partial class {ctx.className} \{"
  ]
  let mut types : Std.HashMap String IRType := {}
  for d in decls do
    if d.params.isEmpty then
      types := types.insert (← toCName d.name) d.resultType
  let mut declIdx : Std.HashMap Name Nat := {}
  for h : i in [0:decls.size] do
    declIdx := declIdx.insert decls[i].name i
  for d in decls do
    withReader (fun ctx => { ctx with declIdx := declIdx }) (emitDecl d)
  emitInitFn info initClass types
  -- exported functions (`@[export]`), registered in `LeanExports`
  emitLn "public static void __RegisterExports() {"
  for d in decls do
    if let .fdecl f xs ty .. := d then
      if let some (.str .anonymous s) := getExportNameFor? (← getEnv) f then
        if xs.isEmpty then
          if ty.isObj then
            emitLn s!"LeanExports.Register(\"{s}\", (nint)(delegate*<Obj>)&__get_{s});"
        else
          emitLn s!"LeanExports.Register(\"{s}\", (nint)({exportFnType xs ty})&{s});"
  emitLn "}"
  -- getters for exported constants
  for d in decls do
    if let .fdecl f xs ty .. := d then
      if xs.isEmpty && ty.isObj then
        if let some (.str .anonymous s) := getExportNameFor? (← getEnv) f then
          emitLn s!"static Obj __get_{s}() => {s};"
  emitMainFnIfNeeded decls
  emitLn "}"

/-! ## Driver -/

def collectExterns (env : Environment) (decls : Array Decl) (owners : Std.HashMap String String)
    (acc : Std.HashMap String String) : Std.HashMap String String := Id.run do
  let mut acc := acc
  for d in decls do
    if let .extern f ps ty ext := d then
      match getExternEntryFor ext `c with
      | some (.standard _ fn) =>
        unless owners.contains fn do
          let sig := String.intercalate ", " (ps.toList.filter (fun p => !p.ty.isErased && !p.ty.isVoid) |>.map (fun p => toCSType p.ty))
          acc := acc.insert fn s!"standard {toCSType ty} {fn}({sig})  -- {f}"
      | some (.inline _ pat) =>
        let sig := String.intercalate ", " (ps.toList.map (fun p => toCSType p.ty))
        acc := acc.insert s!"inline:{pat}" s!"inline {toCSType ty} [{pat}] ({sig})  -- {f}"
      | some (.adhoc _) =>
        let fn := getSymbolStem env f
        acc := acc.insert fn s!"adhoc {toCSType ty} {fn}  -- {f}"
      | _ => pure ()
  return acc

end EmitCS

open EmitCS in
def main (args : List String) : IO UInt32 := do
  let sysroot :: cdir :: outdir :: roots := args | do
    IO.eprintln "usage: EmitCSharp <sysroot> <cdir> <outdir> <RootModule>..."
    return 1
  initSearchPath sysroot
  let imports := roots.toArray.map (fun s => ({ module := s.toName } : Import))
  let env ← importModules (loadExts := false) (level := .private) imports {}
  let modNames := env.header.moduleNames
  IO.println s!"modules: {modNames.size}"
  -- ownership map
  let mut owners : Std.HashMap String String := {}
  let mut initClass : Std.HashMap String String := {}
  for h : idx in [0:modNames.size] do
    let modName := modNames[idx]
    let cls := mangleModName modName
    let pkg? := env.getModulePackageByIdx? idx
    initClass := initClass.insert (mkModuleInitializationFunctionName modName pkg?) cls
    for d in declMapExt.getModuleIREntries env idx do
      if let .fdecl f .. := d then
        let c := match getExportNameFor? env f with
          | some (.str .anonymous s) => s
          | _ => shortName (if f == `main then "_lean_main" else getSymbolStem env f)
        owners := owners.insert c cls
  let mut externs : Std.HashMap String String := {}
  let mut exportsList : Array String := #[]
  let mut manifest := ""
  let mut failures := 0
  for h : idx in [0:modNames.size] do
    let modName := modNames[idx]
    let cls := mangleModName modName
    let decls := declMapExt.getModuleIREntries env idx
    externs := collectExterns env decls owners externs
    for d in decls do
      if let .fdecl f xs ty .. := d then
        if let some (.str .anonymous s) := getExportNameFor? env f then
          exportsList := exportsList.push s!"{s}\t{exportFnType xs ty}\t{f}\t{cls}"
    let relPath := modName.components.foldl (fun p c => if p.isEmpty then c.toString else p ++ "/" ++ c.toString) ""
    let cpath : System.FilePath := cdir ++ "/" ++ relPath ++ ".c"
    let pkg? := env.getModulePackageByIdx? idx
    let stem := (mkModuleInitializationFunctionName modName pkg?).drop "initialize_".length |>.copy
    let info ← if (← cpath.pathExists) then
        pure (parseInit (← IO.FS.readFile cpath) stem)
      else
        IO.eprintln s!"warning: missing C file {cpath}"
        pure {}
    let ctx : Ctx := { env, owners, modName, className := cls, eager := eagerNames info }
    match (emitModule decls info initClass ctx).run "" with
    | .ok _ out =>
      let outPath : System.FilePath := outdir ++ "/" ++ relPath ++ ".cs"
      if let some dir := outPath.parent then IO.FS.createDirAll dir
      IO.FS.writeFile outPath out
      let deps := (env.header.moduleData[idx]!.imports.map (·.module.toString)).toList
      manifest := manifest ++ s!"{modName}\t{relPath}.cs\t{(out.splitOn "\n").length}\t{String.intercalate "," deps}\n"
    | .error err _ =>
      failures := failures + 1
      IO.eprintln s!"error in module {modName}: {err}"
  IO.FS.writeFile (outdir ++ "/manifest.tsv") manifest
  -- registry of all modules
  let mut reg := "// <auto-generated/>\n#pragma warning disable\nusing LeanSharp.Runtime;\nnamespace LeanSharp.Compiled;\n"
  reg := reg ++ "public static unsafe class LeanModules {\n"
  reg := reg ++ "public static void RegisterExports() {\n"
  for m in modNames do
    reg := reg ++ s!"{mangleModName m}.__RegisterExports();\n"
  reg := reg ++ "}\n"
  reg := reg ++ "/// <summary>Initializer of a compiled module, by module name (null if unknown).</summary>\n"
  reg := reg ++ "public static delegate*<byte, Obj> GetInitializer(string mod) {\nswitch (mod) {\n"
  for m in modNames do
    reg := reg ++ s!"case {quoteString m.toString}: return &{mangleModName m}.initialize;\n"
  reg := reg ++ "default: return null;\n}\n}\n"
  reg := reg ++ "/// <summary>C# class implementing a compiled module (null if unknown).</summary>\n"
  reg := reg ++ "public static System.Type GetModuleClass(string mod) {\nswitch (mod) {\n"
  for m in modNames do
    reg := reg ++ s!"case {quoteString m.toString}: return typeof({mangleModName m});\n"
  reg := reg ++ "default: return null;\n}\n}\n"
  reg := reg ++ "public static readonly string[] ModuleNames = {\n"
  for m in modNames do
    reg := reg ++ s!"{quoteString m.toString},\n"
  reg := reg ++ "};\n}\n"
  IO.FS.writeFile (outdir ++ "/_LeanModules.cs") reg
  let externLines := externs.toArray.map (·.2) |>.qsort (· < ·)
  IO.FS.writeFile (outdir ++ "/externs.txt") (String.intercalate "\n" externLines.toList)
  IO.FS.writeFile (outdir ++ "/exports.txt") (String.intercalate "\n" (exportsList.qsort (· < ·)).toList)
  IO.println s!"done, {failures} failures"
  return if failures == 0 then 0 else 1
