// Builds the Lean standard library files (`.olean`, `.ilean`, `.ir`) of `Init`, `Std`, `Lean` and
// `Lake` from the Lean sources with LeanSharp itself, so that no native Lean build is needed to
// obtain a sysroot.

using System.Text;

namespace LeanSharp;

/// <summary>
/// Compiles the Lean core libraries from a checkout of the Lean sources into a sysroot
/// (`<sysroot>/lib/lean`). This is what Lean's own build does with Lake and the file
/// `src/lakefile.toml`, except that only the library files are produced (no C compilation).
/// The sources must be those of the Lean version LeanSharp was generated from
/// (<see cref="LeanVersion"/>).
/// </summary>
public static class LeanStdlib
{
    /// <summary>The Lean commit the compiled Lean code of LeanSharp corresponds to.</summary>
    public static string LeanVersion => LeanSharp.Runtime.LeanRt.LEAN_GITHASH;

    /// <summary>The libraries built by default.</summary>
    public static readonly string[] DefaultTargets = { "Init", "Std", "Lean", "LeanExport", "Lake", "LakeMain", "LeanChecker", "LeanIR" };

    /// <summary>Lean's command-line tools that are Lean programs: `<sysroot>/bin/<name>` runs the module's `main` with the interpreter.</summary>
    static readonly (string exe, string module)[] s_tools = { ("leanchecker", "LeanChecker"), ("leanexport", "LeanExport"), ("leanir", "LeanIR") };

    /// <summary>
    /// Shared libraries of a native Lean installation that Lake passes to `lean --load-dynlib`
    /// (for modules that import `Lake` with precompilation). Here they are stubs: the code is
    /// part of LeanSharp itself.
    /// </summary>
    static readonly string[] s_sharedLibs = { "Lake_shared", "leanshared", "leanshared_1", "leanshared_2", "Init_shared" };

    /// <summary>The Lake configuration used for the build (`leanSrcDir`: the `src` directory of the Lean repository).</summary>
    public static string Lakefile(string leanSrcDir, string sysroot)
    {
        static string Q(string s) => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by LeanSharp (LeanStdlib.Build); mirrors src/lakefile.toml.in of the Lean repository.");
        sb.AppendLine("name = \"lean4\"");
        sb.AppendLine("bootstrap = true");
        sb.AppendLine("defaultTargets = [" + string.Join(", ", DefaultTargets.Select(Q)) + "]");
        sb.AppendLine("buildType = \"Release\"");
        sb.AppendLine("buildDir = " + Q(sysroot));
        sb.AppendLine("enableArtifactCache = false");
        sb.AppendLine("restoreAllArtifacts = true");
        sb.AppendLine("srcDir = " + Q(leanSrcDir));
        sb.AppendLine("irDir = \"lib/temp\"");
        sb.AppendLine("leanLibDir = \"lib/lean\"");
        sb.AppendLine("nativeLibDir = \"lib/lean\"");
        sb.AppendLine("moreLeanArgs = [\"-Dinterpreter.prefer_native=false\", \"-Dpp.rawOnError=true\"]");
        sb.AppendLine("leanOptions.linter.coreInternal = true");
        sb.AppendLine("[[lean_lib]]\nname = \"Init\"");
        sb.AppendLine("[[lean_lib]]\nname = \"Std\"");
        sb.AppendLine("[[lean_lib]]\nname = \"Lean\"\nglobs = [\"Lean\", \"Lean.Compiler.IR.EmitLLVM\", \"Lean.Compiler.LCNF.Probing\"]");
        sb.AppendLine("[[lean_lib]]\nname = \"LeanExport\"\nglobs = [\"LeanExport\", \"LeanExport.*\"]");
        sb.AppendLine("[[lean_lib]]\nname = \"Lake\"\nsrcDir = \"lake\"\nglobs = [\"Lake.*\"]");
        sb.AppendLine("[[lean_lib]]\nname = \"LakeMain\"\nsrcDir = \"lake\"");
        sb.AppendLine("[[lean_lib]]\nname = \"LeanChecker\"");
        sb.AppendLine("[[lean_lib]]\nname = \"LeanIR\"");
        return sb.ToString();
    }

    /// <summary>
    /// `<sysroot>/src/lean` is where Lean looks for the library sources (go-to-definition and
    /// references in the language server); Lean's own build makes it a link to `src`.
    /// </summary>
    static void LinkSources(string leanSrcDir, string sysroot)
    {
        try
        {
            var link = Path.Combine(sysroot, "src", "lean");
            if (Directory.Exists(link) || File.Exists(link)) return;
            Directory.CreateDirectory(Path.Combine(sysroot, "src"));
            Directory.CreateSymbolicLink(link, leanSrcDir);
        }
        catch (IOException) { }                 // e.g. no privilege to create links on Windows:
        catch (UnauthorizedAccessException) { } // set `LEAN_SRC_PATH` instead
    }

    /// <summary>
    /// Builds the libraries into <paramref name="sysroot"/> (created if needed) and makes it the
    /// current sysroot (<see cref="LeanSysroot.Root"/>). Incremental: a second call only
    /// rebuilds what changed. A full build takes a few minutes per core-hour of work (about
    /// 2,560 modules) and around 10 GB of memory with 24 threads; pass e.g. `-j4`-style limits
    /// through <paramref name="environment"/> (`LEAN_NUM_THREADS`) on smaller machines.
    /// </summary>
    /// <param name="leanSrcDir">The `src` directory of the Lean repository (contains `Init.lean`).</param>
    /// <param name="targets">Lake targets (default: all libraries).</param>
    public static LeanResult Build(string leanSrcDir, string sysroot, string[] targets = null,
        IDictionary<string, string> environment = null, Action<string> onOutputLine = null)
    {
        leanSrcDir = Path.GetFullPath(leanSrcDir);
        sysroot = Path.GetFullPath(sysroot);
        if (!File.Exists(Path.Combine(leanSrcDir, "Init.lean")))
            throw new DirectoryNotFoundException($"'{leanSrcDir}' is not the 'src' directory of a Lean checkout (Init.lean not found)");
        Directory.CreateDirectory(Path.Combine(sysroot, "lib", "lean"));
        var lakefile = Path.Combine(sysroot, "lakefile.toml");
        var text = Lakefile(leanSrcDir, sysroot);
        if (!File.Exists(lakefile) || File.ReadAllText(lakefile) != text) File.WriteAllText(lakefile, text);
        LinkSources(leanSrcDir, sysroot);
        LeanSysroot.Root = sysroot;
        var project = new LeanProject(sysroot);
        if (environment != null)
            foreach (var kv in environment) project.Environment[kv.Key] = kv.Value;
        var result = project.Run("lake", new[] { "build" }.Concat(targets ?? Array.Empty<string>()).ToArray(), null, onOutputLine);
        if (result.Success)
        {
            string libDir = Path.Combine(sysroot, "lib", "lean");
            foreach (var (exe, module) in s_tools)
                if (File.Exists(Path.Combine(libDir, module + ".olean")))
                    ManagedToolchain.WriteLauncher(Path.Combine(sysroot, "bin", exe), module, new[] { libDir });
            string prefix = OperatingSystem.IsWindows() ? "" : "lib";
            string ext = OperatingSystem.IsWindows() ? ".dll" : OperatingSystem.IsMacOS() ? ".dylib" : ".so";
            foreach (var lib in s_sharedLibs)
            {
                string path = Path.Combine(libDir, prefix + lib + ext);
                if (!File.Exists(path)) File.WriteAllText(path, LeanSharp.Runtime.LeanRt.ManagedLibMagic + "\n");
            }
        }
        return result;
    }
}
