<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RootNamespace>NumbersCheck</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/LeanSharp.Runtime/Core/**/*.cs" />
    <Compile Include="../../src/LeanSharp.Runtime/Numbers/**/*.cs" />
    <Compile Include="*.cs" />
    <None Include="expected.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
