#!/usr/bin/env python3
"""Generates src/LeanSharp.Runtime/Core/LeanRt.Apply.cs (port of runtime/apply.cpp)."""
MAX = 16
out = []
w = out.append
w("// <auto-generated by tools/gen_apply.py/> Port of runtime/apply.cpp")
w("using System.Runtime.CompilerServices;")
w("namespace LeanSharp.Runtime;")
w("public static unsafe partial class LeanRt {")

def fnty(n):
    return "delegate*<" + ", ".join(["Obj"] * (n + 1)) + ">"

# curry: call function pointer with n args taken from array
w("public static Obj lean_curry(void* f, int n, Obj[] a, int off = 0) {")
w("switch (n) {")
for n in range(1, MAX + 1):
    args = ", ".join(f"a[off+{i}]" for i in range(n))
    w(f"case {n}: return (({fnty(n)})f)({args});")
w("default: { if (off == 0 && a.Length == n) return ((delegate*<Obj[], Obj>)f)(a); var b = new Obj[n]; Array.Copy(a, off, b, 0, n); return ((delegate*<Obj[], Obj>)f)(b); }")
w("}")
w("}")

w("""static Obj FixArgs(Obj f, Obj[] a, int off, int n) {
    var c = Unsafe.As<Closure>(f);
    int arity = c.m_arity, fixed_ = c.m_num_fixed;
    var r = new Closure { m_tag = (byte)LeanClosure, m_fun = c.m_fun, m_arity = (ushort)arity, m_num_fixed = (ushort)(fixed_ + n), m_objs = new Obj[fixed_ + n] };
    if (!lean_is_exclusive(f)) {
        for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); r.m_objs[i] = x; }
        lean_dec_ref(f);
    } else {
        Array.Copy(c.m_objs, r.m_objs, fixed_);
    }
    Array.Copy(a, off, r.m_objs, fixed_, n);
    return r;
}""")

for n in range(1, MAX + 1):
    params = ", ".join(f"Obj a{i}" for i in range(1, n + 1))
    alist = ", ".join(f"a{i}" for i in range(1, n + 1))
    w(f"public static Obj lean_apply_{n}(Obj f, {params}) {{")
    w("if (f.m_tag == LeanBoxTag) { " + " ".join(f"lean_dec(a{i});" for i in range(1, n + 1)) + " return f; }")
    w("var c = Unsafe.As<Closure>(f);")
    w("int arity = c.m_arity; int fixed_ = c.m_num_fixed;")
    w(f"if (arity == fixed_ + {n}) {{")
    w("  var fx = c.m_objs;")
    w("  bool excl = lean_is_exclusive(f);")
    w("  if (!excl) { for (int i = 0; i < fixed_; i++) lean_inc(fx[i]); }")
    w("  Obj r;")
    w("  switch (arity) {")
    for arity in range(n, MAX + 1):
        fixed = arity - n
        args = ", ".join([f"fx[{i}]" for i in range(fixed)] + [f"a{i}" for i in range(1, n + 1)])
        w(f"  case {arity}: r = (({fnty(arity)})c.m_fun)({args}); break;")
    w("  default: {")
    w("    var args = new Obj[arity];")
    w("    Array.Copy(fx, args, fixed_);")
    for i in range(1, n + 1):
        w(f"    args[fixed_ + {i - 1}] = a{i};")
    w("    r = ((delegate*<Obj[], Obj>)c.m_fun)(args); break; }")
    w("  }")
    w("  if (!excl) lean_dec_ref(f);")
    w("  return r;")
    w(f"}} else if (arity < fixed_ + {n}) {{")
    w(f"  var as_ = new Obj[] {{ {alist} }};")
    w("  var args = new Obj[arity];")
    w("  for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }")
    w("  Array.Copy(as_, 0, args, fixed_, arity - fixed_);")
    w("  var new_f = lean_curry(c.m_fun, arity, args);")
    w("  lean_dec_ref(f);")
    w(f"  return lean_apply_n_off(new_f, {n} + fixed_ - arity, as_, arity - fixed_);")
    w("} else {")
    w(f"  return FixArgs(f, new Obj[] {{ {alist} }}, 0, {n});")
    w("}")
    w("}")

# apply_n with offset
w("public static Obj lean_apply_n_off(Obj f, int n, Obj[] a, int off) {")
w("switch (n) {")
for n in range(1, MAX + 1):
    args = ", ".join(f"a[off+{i}]" for i in range(n))
    w(f"case {n}: return lean_apply_{n}(f, {args});")
w("default: return lean_apply_m_off(f, n, a, off);")
w("}")
w("}")
w("public static Obj lean_apply_n(Obj f, uint n, Obj[] a) => lean_apply_n_off(f, (int)n, a, 0);")
w("public static Obj lean_apply_m(Obj f, uint n, Obj[] a) => lean_apply_m_off(f, (int)n, a, 0);")
w("""public static Obj lean_apply_m_off(Obj f, int n, Obj[] a, int off) {
    if (f.m_tag == LeanBoxTag) { for (int i = 0; i < n; i++) lean_dec(a[off + i]); return f; }
    var c = Unsafe.As<Closure>(f);
    int arity = c.m_arity, fixed_ = c.m_num_fixed;
    if (arity == fixed_ + n) {
        var args = new Obj[arity];
        for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
        Array.Copy(a, off, args, fixed_, n);
        var r = ((delegate*<Obj[], Obj>)c.m_fun)(args);
        lean_dec_ref(f);
        return r;
    } else if (arity < fixed_ + n) {
        int m = arity - fixed_;
        Obj new_f;
        if (arity > LEAN_CLOSURE_MAX_ARGS) {
            var args = new Obj[arity];
            for (int i = 0; i < fixed_; i++) { var x = c.m_objs[i]; lean_inc(x); args[i] = x; }
            Array.Copy(a, off, args, fixed_, m);
            new_f = ((delegate*<Obj[], Obj>)c.m_fun)(args);
            lean_dec_ref(f);
        } else {
            new_f = lean_apply_n_off(f, m, a, off);
        }
        return lean_apply_n_off(new_f, n - m, a, off + m);
    } else {
        return FixArgs(f, a, off, n);
    }
}""")
w("}")
import pathlib, sys
p = pathlib.Path(__file__).resolve().parent.parent / "src/LeanSharp.Runtime/Core/LeanRt.Apply.cs"
p.write_text("\n".join(out) + "\n")
print("wrote", p)
