#!/usr/bin/env python3
"""Generate throwing stubs for runtime externs that are not implemented yet.
usage: gen_stubs.py <externs.txt> <runtime src dir> <out.cs>
Only externs whose name is not defined as a `public static` method under the runtime dir are stubbed."""
import re, sys, pathlib
externs, rtdir, out = sys.argv[1], pathlib.Path(sys.argv[2]), sys.argv[3]
defined = set()
for f in [f for f in rtdir.rglob('*.cs') if '/Cadical/' not in str(f) and '/_TempStubs/' not in str(f)]:
    for m in re.finditer(r'public\s+static\s+[\w<>\[\]\*, ]+?\s+(lean_\w+|\w+)\s*(<[^>]*>)?\s*\(', f.read_text()):
        defined.add(m.group(1))
lines = []
for l in open(externs):
    m = re.match(r'(standard|adhoc) (\S+) (\w+)\((.*?)\)\s+--', l)
    if not m: continue
    _, ret, name, args = m.groups()
    if name in defined: continue
    ps = [a.strip() for a in args.split(',') if a.strip()]
    params = ", ".join(f"{t} a{i}" for i, t in enumerate(ps))
    lines.append(f'    public static {ret} {name}({params}) => throw new NotImplementedException("{name}");')
    defined.add(name)
src = "// <auto-generated/> stubs for unimplemented externs\nnamespace LeanSharp.Runtime;\npublic static unsafe partial class LeanRt {\n" + "\n".join(lines) + "\n}\n"
pathlib.Path(out).write_text(src)
print(f"{len(lines)} stubs")
