// Access to the functions implemented in Lean and exported with `@[export]` that the kernel
// calls (see docs/lean-exports.txt). All arguments are owned (exported Lean functions never have
// borrowed parameters) and all results are owned. Generated by a script; keep in sync with
// docs/lean-exports.txt.

using LeanSharp.Runtime;

namespace LeanSharp.Kernel;

internal static unsafe class KX
{
    static delegate*<Obj, Obj, Obj> s_nameMkString;
    public static Obj NameMkString(Obj a0, Obj a1)
    {
        var f = s_nameMkString;
        if (f == null) s_nameMkString = f = (delegate*<Obj, Obj, Obj>)LeanExports.Get("lean_name_mk_string");
        return f(a0, a1);
    }

    static delegate*<Obj, Obj, Obj> s_nameMkNumeral;
    public static Obj NameMkNumeral(Obj a0, Obj a1)
    {
        var f = s_nameMkNumeral;
        if (f == null) s_nameMkNumeral = f = (delegate*<Obj, Obj, Obj>)LeanExports.Get("lean_name_mk_numeral");
        return f(a0, a1);
    }

    static delegate*<Obj, Obj, Obj> s_nameAppendAfter;
    public static Obj NameAppendAfter(Obj a0, Obj a1)
    {
        var f = s_nameAppendAfter;
        if (f == null) s_nameAppendAfter = f = (delegate*<Obj, Obj, Obj>)LeanExports.Get("lean_name_append_after");
        return f(a0, a1);
    }

    static delegate*<Obj, Obj, Obj> s_nameAppendIndexAfter;
    public static Obj NameAppendIndexAfter(Obj a0, Obj a1)
    {
        var f = s_nameAppendIndexAfter;
        if (f == null) s_nameAppendIndexAfter = f = (delegate*<Obj, Obj, Obj>)LeanExports.Get("lean_name_append_index_after");
        return f(a0, a1);
    }

    static delegate*<Obj, Obj> s_levelMkZero;
    public static Obj LevelMkZero(Obj a0)
    {
        var f = s_levelMkZero;
        if (f == null) s_levelMkZero = f = (delegate*<Obj, Obj>)LeanExports.Get("lean_level_mk_zero");
        return f(a0);
    }

    static delegate*<Obj, Obj> s_levelMkSucc;
    public static Obj LevelMkSucc(Obj a0)
    {
        var f = s_levelMkSucc;
        if (f == null) s_levelMkSucc = f = (delegate*<Obj, Obj>)LeanExports.Get("lean_level_mk_succ");
        return f(a0);
    }

    static delegate*<Obj, Obj, Obj> s_levelMkMax;
    public static Obj LevelMkMax(Obj a0, Obj a1)
    {
        var f = s_levelMkMax;
        if (f == null) s_levelMkMax = f = (delegate*<Obj, Obj, Obj>)LeanExports.Get("lean_level_mk_max");
        return f(a0, a1);
    }

    static delegate*<Obj, Obj, Obj> s_levelMkIMax;
    public static Obj LevelMkIMax(Obj a0, Obj a1)
    {
        var f = s_levelMkIMax;
        if (f == null) s_levelMkIMax = f = (delegate*<Obj, Obj, Obj>)LeanExports.Get("lean_level_mk_imax");
        return f(a0, a1);
    }

    static delegate*<Obj, Obj> s_levelMkParam;
    public static Obj LevelMkParam(Obj a0)
    {
        var f = s_levelMkParam;
        if (f == null) s_levelMkParam = f = (delegate*<Obj, Obj>)LeanExports.Get("lean_level_mk_param");
        return f(a0);
    }

    static delegate*<Obj, Obj> s_exprMkBVar;
    public static Obj ExprMkBVar(Obj a0)
    {
        var f = s_exprMkBVar;
        if (f == null) s_exprMkBVar = f = (delegate*<Obj, Obj>)LeanExports.Get("lean_expr_mk_bvar");
        return f(a0);
    }

    static delegate*<Obj, Obj> s_exprMkFVar;
    public static Obj ExprMkFVar(Obj a0)
    {
        var f = s_exprMkFVar;
        if (f == null) s_exprMkFVar = f = (delegate*<Obj, Obj>)LeanExports.Get("lean_expr_mk_fvar");
        return f(a0);
    }

    static delegate*<Obj, Obj> s_exprMkSort;
    public static Obj ExprMkSort(Obj a0)
    {
        var f = s_exprMkSort;
        if (f == null) s_exprMkSort = f = (delegate*<Obj, Obj>)LeanExports.Get("lean_expr_mk_sort");
        return f(a0);
    }

    static delegate*<Obj, Obj, Obj> s_exprMkConst;
    public static Obj ExprMkConst(Obj a0, Obj a1)
    {
        var f = s_exprMkConst;
        if (f == null) s_exprMkConst = f = (delegate*<Obj, Obj, Obj>)LeanExports.Get("lean_expr_mk_const");
        return f(a0, a1);
    }

    static delegate*<Obj, Obj, Obj> s_exprMkApp;
    public static Obj ExprMkApp(Obj a0, Obj a1)
    {
        var f = s_exprMkApp;
        if (f == null) s_exprMkApp = f = (delegate*<Obj, Obj, Obj>)LeanExports.Get("lean_expr_mk_app");
        return f(a0, a1);
    }

    static delegate*<Obj, Obj, Obj, byte, Obj> s_exprMkLambda;
    public static Obj ExprMkLambda(Obj a0, Obj a1, Obj a2, byte a3)
    {
        var f = s_exprMkLambda;
        if (f == null) s_exprMkLambda = f = (delegate*<Obj, Obj, Obj, byte, Obj>)LeanExports.Get("lean_expr_mk_lambda");
        return f(a0, a1, a2, a3);
    }

    static delegate*<Obj, Obj, Obj, byte, Obj> s_exprMkForall;
    public static Obj ExprMkForall(Obj a0, Obj a1, Obj a2, byte a3)
    {
        var f = s_exprMkForall;
        if (f == null) s_exprMkForall = f = (delegate*<Obj, Obj, Obj, byte, Obj>)LeanExports.Get("lean_expr_mk_forall");
        return f(a0, a1, a2, a3);
    }

    static delegate*<Obj, Obj, Obj, Obj, byte, Obj> s_exprMkLet;
    public static Obj ExprMkLet(Obj a0, Obj a1, Obj a2, Obj a3, byte a4)
    {
        var f = s_exprMkLet;
        if (f == null) s_exprMkLet = f = (delegate*<Obj, Obj, Obj, Obj, byte, Obj>)LeanExports.Get("lean_expr_mk_let");
        return f(a0, a1, a2, a3, a4);
    }

    static delegate*<Obj, Obj> s_exprMkLit;
    public static Obj ExprMkLit(Obj a0)
    {
        var f = s_exprMkLit;
        if (f == null) s_exprMkLit = f = (delegate*<Obj, Obj>)LeanExports.Get("lean_expr_mk_lit");
        return f(a0);
    }

    static delegate*<Obj, Obj, Obj> s_exprMkMData;
    public static Obj ExprMkMData(Obj a0, Obj a1)
    {
        var f = s_exprMkMData;
        if (f == null) s_exprMkMData = f = (delegate*<Obj, Obj, Obj>)LeanExports.Get("lean_expr_mk_mdata");
        return f(a0, a1);
    }

    static delegate*<Obj, Obj, Obj, Obj> s_exprMkProj;
    public static Obj ExprMkProj(Obj a0, Obj a1, Obj a2)
    {
        var f = s_exprMkProj;
        if (f == null) s_exprMkProj = f = (delegate*<Obj, Obj, Obj, Obj>)LeanExports.Get("lean_expr_mk_proj");
        return f(a0, a1, a2);
    }

    static delegate*<Obj, Obj> s_litType;
    public static Obj LitType(Obj a0)
    {
        var f = s_litType;
        if (f == null) s_litType = f = (delegate*<Obj, Obj>)LeanExports.Get("lean_lit_type");
        return f(a0);
    }

    static delegate*<Obj, Obj> s_exprConsumeTypeAnnotations;
    public static Obj ExprConsumeTypeAnnotations(Obj a0)
    {
        var f = s_exprConsumeTypeAnnotations;
        if (f == null) s_exprConsumeTypeAnnotations = f = (delegate*<Obj, Obj>)LeanExports.Get("lean_expr_consume_type_annotations");
        return f(a0);
    }

    static delegate*<Obj, Obj> s_mkEmptyLocalCtx;
    public static Obj MkEmptyLocalCtx(Obj a0)
    {
        var f = s_mkEmptyLocalCtx;
        if (f == null) s_mkEmptyLocalCtx = f = (delegate*<Obj, Obj>)LeanExports.Get("lean_mk_empty_local_ctx");
        return f(a0);
    }

    static delegate*<Obj, Obj> s_localCtxNumIndices;
    public static Obj LocalCtxNumIndices(Obj a0)
    {
        var f = s_localCtxNumIndices;
        if (f == null) s_localCtxNumIndices = f = (delegate*<Obj, Obj>)LeanExports.Get("lean_local_ctx_num_indices");
        return f(a0);
    }

    static delegate*<Obj, Obj, Obj, Obj, byte, Obj> s_localCtxMkLocalDecl;
    public static Obj LocalCtxMkLocalDecl(Obj a0, Obj a1, Obj a2, Obj a3, byte a4)
    {
        var f = s_localCtxMkLocalDecl;
        if (f == null) s_localCtxMkLocalDecl = f = (delegate*<Obj, Obj, Obj, Obj, byte, Obj>)LeanExports.Get("lean_local_ctx_mk_local_decl");
        return f(a0, a1, a2, a3, a4);
    }

    static delegate*<Obj, Obj, Obj, Obj, Obj, byte, Obj> s_localCtxMkLetDecl;
    public static Obj LocalCtxMkLetDecl(Obj a0, Obj a1, Obj a2, Obj a3, Obj a4, byte a5)
    {
        var f = s_localCtxMkLetDecl;
        if (f == null) s_localCtxMkLetDecl = f = (delegate*<Obj, Obj, Obj, Obj, Obj, byte, Obj>)LeanExports.Get("lean_local_ctx_mk_let_decl");
        return f(a0, a1, a2, a3, a4, a5);
    }

    static delegate*<Obj, Obj, Obj> s_localCtxFind;
    public static Obj LocalCtxFind(Obj a0, Obj a1)
    {
        var f = s_localCtxFind;
        if (f == null) s_localCtxFind = f = (delegate*<Obj, Obj, Obj>)LeanExports.Get("lean_local_ctx_find");
        return f(a0, a1);
    }

    static delegate*<Obj, Obj, Obj, Obj, byte, Obj> s_mkLocalDecl;
    public static Obj MkLocalDecl(Obj a0, Obj a1, Obj a2, Obj a3, byte a4)
    {
        var f = s_mkLocalDecl;
        if (f == null) s_mkLocalDecl = f = (delegate*<Obj, Obj, Obj, Obj, byte, Obj>)LeanExports.Get("lean_mk_local_decl");
        return f(a0, a1, a2, a3, a4);
    }

    static delegate*<Obj, Obj, Obj, Obj, Obj, Obj> s_mkLetDecl;
    public static Obj MkLetDecl(Obj a0, Obj a1, Obj a2, Obj a3, Obj a4)
    {
        var f = s_mkLetDecl;
        if (f == null) s_mkLetDecl = f = (delegate*<Obj, Obj, Obj, Obj, Obj, Obj>)LeanExports.Get("lean_mk_let_decl");
        return f(a0, a1, a2, a3, a4);
    }

    static delegate*<Obj, Obj, Obj> s_environmentAdd;
    public static Obj EnvironmentAdd(Obj a0, Obj a1)
    {
        var f = s_environmentAdd;
        if (f == null) s_environmentAdd = f = (delegate*<Obj, Obj, Obj>)LeanExports.Get("lean_environment_add");
        return f(a0, a1);
    }

    static delegate*<Obj, Obj, Obj> s_environmentFind;
    public static Obj EnvironmentFind(Obj a0, Obj a1)
    {
        var f = s_environmentFind;
        if (f == null) s_environmentFind = f = (delegate*<Obj, Obj, Obj>)LeanExports.Get("lean_environment_find");
        return f(a0, a1);
    }

    static delegate*<Obj, Obj> s_environmentMarkQuotInit;
    public static Obj EnvironmentMarkQuotInit(Obj a0)
    {
        var f = s_environmentMarkQuotInit;
        if (f == null) s_environmentMarkQuotInit = f = (delegate*<Obj, Obj>)LeanExports.Get("lean_environment_mark_quot_init");
        return f(a0);
    }

    static delegate*<Obj, byte> s_environmentQuotInit;
    public static byte EnvironmentQuotInit(Obj a0)
    {
        var f = s_environmentQuotInit;
        if (f == null) s_environmentQuotInit = f = (delegate*<Obj, byte>)LeanExports.Get("lean_environment_quot_init");
        return f(a0);
    }

    static delegate*<Obj, Obj, Obj> s_kernelRecordUnfold;
    public static Obj KernelRecordUnfold(Obj a0, Obj a1)
    {
        var f = s_kernelRecordUnfold;
        if (f == null) s_kernelRecordUnfold = f = (delegate*<Obj, Obj, Obj>)LeanExports.Get("lean_kernel_record_unfold");
        return f(a0, a1);
    }

    static delegate*<Obj, Obj> s_kernelGetDiag;
    public static Obj KernelGetDiag(Obj a0)
    {
        var f = s_kernelGetDiag;
        if (f == null) s_kernelGetDiag = f = (delegate*<Obj, Obj>)LeanExports.Get("lean_kernel_get_diag");
        return f(a0);
    }

    static delegate*<Obj, Obj, Obj> s_kernelSetDiag;
    public static Obj KernelSetDiag(Obj a0, Obj a1)
    {
        var f = s_kernelSetDiag;
        if (f == null) s_kernelSetDiag = f = (delegate*<Obj, Obj, Obj>)LeanExports.Get("lean_kernel_set_diag");
        return f(a0, a1);
    }

    static delegate*<Obj, byte> s_kernelDiagIsEnabled;
    public static byte KernelDiagIsEnabled(Obj a0)
    {
        var f = s_kernelDiagIsEnabled;
        if (f == null) s_kernelDiagIsEnabled = f = (delegate*<Obj, byte>)LeanExports.Get("lean_kernel_diag_is_enabled");
        return f(a0);
    }

    static delegate*<Obj, Obj> s_elabEnvironmentToKernelEnv;
    public static Obj ElabEnvironmentToKernelEnv(Obj a0)
    {
        var f = s_elabEnvironmentToKernelEnv;
        if (f == null) s_elabEnvironmentToKernelEnv = f = (delegate*<Obj, Obj>)LeanExports.Get("lean_elab_environment_to_kernel_env");
        return f(a0);
    }

    static delegate*<Obj, Obj, Obj, Obj> s_elabEnvironmentUpdateBaseAfterKernelAdd;
    public static Obj ElabEnvironmentUpdateBaseAfterKernelAdd(Obj a0, Obj a1, Obj a2)
    {
        var f = s_elabEnvironmentUpdateBaseAfterKernelAdd;
        if (f == null) s_elabEnvironmentUpdateBaseAfterKernelAdd = f = (delegate*<Obj, Obj, Obj, Obj>)LeanExports.Get("lean_elab_environment_update_base_after_kernel_add");
        return f(a0, a1, a2);
    }

    static delegate*<Obj, Obj, Obj, Obj, Obj, byte, Obj, Obj> s_mkDefinitionVal;
    public static Obj MkDefinitionVal(Obj a0, Obj a1, Obj a2, Obj a3, Obj a4, byte a5, Obj a6)
    {
        var f = s_mkDefinitionVal;
        if (f == null) s_mkDefinitionVal = f = (delegate*<Obj, Obj, Obj, Obj, Obj, byte, Obj, Obj>)LeanExports.Get("lean_mk_definition_val");
        return f(a0, a1, a2, a3, a4, a5, a6);
    }

    static delegate*<Obj, Obj, Obj, byte, Obj> s_mkQuotVal;
    public static Obj MkQuotVal(Obj a0, Obj a1, Obj a2, byte a3)
    {
        var f = s_mkQuotVal;
        if (f == null) s_mkQuotVal = f = (delegate*<Obj, Obj, Obj, byte, Obj>)LeanExports.Get("lean_mk_quot_val");
        return f(a0, a1, a2, a3);
    }

    static delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, byte, byte, byte, Obj> s_mkInductiveVal;
    public static Obj MkInductiveVal(Obj a0, Obj a1, Obj a2, Obj a3, Obj a4, Obj a5, Obj a6, Obj a7, byte a8, byte a9, byte a10)
    {
        var f = s_mkInductiveVal;
        if (f == null) s_mkInductiveVal = f = (delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, byte, byte, byte, Obj>)LeanExports.Get("lean_mk_inductive_val");
        return f(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10);
    }

    static delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, byte, Obj> s_mkConstructorVal;
    public static Obj MkConstructorVal(Obj a0, Obj a1, Obj a2, Obj a3, Obj a4, Obj a5, Obj a6, byte a7)
    {
        var f = s_mkConstructorVal;
        if (f == null) s_mkConstructorVal = f = (delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, byte, Obj>)LeanExports.Get("lean_mk_constructor_val");
        return f(a0, a1, a2, a3, a4, a5, a6, a7);
    }

    static delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, byte, byte, Obj> s_mkRecursorVal;
    public static Obj MkRecursorVal(Obj a0, Obj a1, Obj a2, Obj a3, Obj a4, Obj a5, Obj a6, Obj a7, Obj a8, byte a9, byte a10)
    {
        var f = s_mkRecursorVal;
        if (f == null) s_mkRecursorVal = f = (delegate*<Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, Obj, byte, byte, Obj>)LeanExports.Get("lean_mk_recursor_val");
        return f(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10);
    }

    static delegate*<Obj, Obj, Obj, byte, Obj> s_mkInductiveDecl;
    public static Obj MkInductiveDecl(Obj a0, Obj a1, Obj a2, byte a3)
    {
        var f = s_mkInductiveDecl;
        if (f == null) s_mkInductiveDecl = f = (delegate*<Obj, Obj, Obj, byte, Obj>)LeanExports.Get("lean_mk_inductive_decl");
        return f(a0, a1, a2, a3);
    }

    static delegate*<Obj, Obj, Obj> s_getLMVarAssignment;
    public static Obj GetLMVarAssignment(Obj a0, Obj a1)
    {
        var f = s_getLMVarAssignment;
        if (f == null) s_getLMVarAssignment = f = (delegate*<Obj, Obj, Obj>)LeanExports.Get("lean_get_lmvar_assignment");
        return f(a0, a1);
    }

    static delegate*<Obj, Obj, Obj, Obj> s_assignLMVar;
    public static Obj AssignLMVar(Obj a0, Obj a1, Obj a2)
    {
        var f = s_assignLMVar;
        if (f == null) s_assignLMVar = f = (delegate*<Obj, Obj, Obj, Obj>)LeanExports.Get("lean_assign_lmvar");
        return f(a0, a1, a2);
    }

    static delegate*<Obj, Obj, Obj> s_getMVarAssignment;
    public static Obj GetMVarAssignment(Obj a0, Obj a1)
    {
        var f = s_getMVarAssignment;
        if (f == null) s_getMVarAssignment = f = (delegate*<Obj, Obj, Obj>)LeanExports.Get("lean_get_mvar_assignment");
        return f(a0, a1);
    }

    static delegate*<Obj, Obj, Obj> s_getDelayedMVarAssignment;
    public static Obj GetDelayedMVarAssignment(Obj a0, Obj a1)
    {
        var f = s_getDelayedMVarAssignment;
        if (f == null) s_getDelayedMVarAssignment = f = (delegate*<Obj, Obj, Obj>)LeanExports.Get("lean_get_delayed_mvar_assignment");
        return f(a0, a1);
    }

    static delegate*<Obj, Obj> s_delayedMVarAssignmentFVars;
    public static Obj DelayedMVarAssignmentFVars(Obj a0)
    {
        var f = s_delayedMVarAssignmentFVars;
        if (f == null) s_delayedMVarAssignmentFVars = f = (delegate*<Obj, Obj>)LeanExports.Get("lean_delayed_mvar_assignment_fvars");
        return f(a0);
    }

    static delegate*<Obj, Obj> s_delayedMVarAssignmentMVarIdPending;
    public static Obj DelayedMVarAssignmentMVarIdPending(Obj a0)
    {
        var f = s_delayedMVarAssignmentMVarIdPending;
        if (f == null) s_delayedMVarAssignmentMVarIdPending = f = (delegate*<Obj, Obj>)LeanExports.Get("lean_delayed_mvar_assignment_mvar_id_pending");
        return f(a0);
    }

    static delegate*<Obj, Obj, Obj, Obj> s_assignMVar;
    public static Obj AssignMVar(Obj a0, Obj a1, Obj a2)
    {
        var f = s_assignMVar;
        if (f == null) s_assignMVar = f = (delegate*<Obj, Obj, Obj, Obj>)LeanExports.Get("lean_assign_mvar");
        return f(a0, a1, a2);
    }

    static delegate*<Obj, Obj, byte> s_dataValueBeq;
    public static byte DataValueBeq(Obj a0, Obj a1)
    {
        var f = s_dataValueBeq;
        if (f == null) s_dataValueBeq = f = (delegate*<Obj, Obj, byte>)LeanExports.Get("lean_data_value_beq");
        return f(a0, a1);
    }

    static delegate*<Obj, byte> s_dataValueBool;
    public static byte DataValueBool(Obj a0)
    {
        var f = s_dataValueBool;
        if (f == null) s_dataValueBool = f = (delegate*<Obj, byte>)LeanExports.Get("lean_data_value_bool");
        return f(a0);
    }

    static delegate*<Obj, Obj, byte> s_isTraceClassEnabled;
    public static byte IsTraceClassEnabled(Obj a0, Obj a1)
    {
        var f = s_isTraceClassEnabled;
        if (f == null) s_isTraceClassEnabled = f = (delegate*<Obj, Obj, byte>)LeanExports.Get("lean_is_trace_class_enabled");
        return f(a0, a1);
    }

    static delegate*<Obj, Obj> s_iOEPrint;
    public static Obj IOEPrint(Obj a0)
    {
        var f = s_iOEPrint;
        if (f == null) s_iOEPrint = f = (delegate*<Obj, Obj>)LeanExports.Get("lean_io_eprint");
        return f(a0);
    }

}
